### ISSUE TITLE
New Utility options - Select all PCs/NPCs

### ISSUE THREAD

**Issue by apoapostolov** [Drental/fvtt-tokenactionhud#10]
Since there is support for group ability checks (I noticed this by a chance in PF2) it would simplify things if there was a quick way via Token Action HUD to select all players or all NPCs in the scene, so next the HUD can be used for a group check/save.

This is mainly useful for the PCs (for group Perception, etc.) so if you feel like it, you can only implement this part.

**Comment by Drental** [comment]
bonus cred for right-click to target all.

**Comment by Larkinabout** [comment]
This might be best as a macro as Token Action HUD's core function is to provide an interface for already selected tokens. Selecting a token in order to select other tokens might muddy the waters?

**Comment by Larkinabout** [comment]
I'm going to close this one as I'd like to keep features within the bounds of the HUD's core function. However, as macros can be added to the HUD, you can add the following script macros to create these functions and add them to the HUD yourself.

### Select all NPCs
```
canvas.tokens.releaseAll();
for (const token of canvas.tokens.children[0].children) { 
  if (token.actor.type === "npc") { 
    token.control({ releaseOthers: false });
  }
}
```

### Select all PCs
```
canvas.tokens.releaseAll();
for (const token of canvas.tokens.children[0].children) { 
  if (token.actor.type === "character" && token.actor.hasPlayerOwner) {
    token.control({ releaseOthers: false });
  }
}
```
The actor types may vary depending on the system.

![tah-select-all](https://user-images.githubusercontent.com/105953297/193694006-ec4745f0-09a7-44b1-8cab-a4fb1dd5fe6a.gif)
