### ISSUE TITLE
Add equip weapon to Strikes list

### ISSUE THREAD

**Issue by Keatnisher** [Drental/fvtt-tokenactionhud#102]
Primary system: PF2e

I'd like to be able to equip/unequip weapons from the HUD. I've largely been having my players ignore the rules for equipping weapons because it takes too long, and is cumbersome to open up the sheet and equip a weapon mid-combat. But if equipping was included part of the token action HUD this would become much easier.

I understand the Strikes list only considers weapons that are already equipped, so I'm not sure how complicated this would be to change. The system just added the weapon equip to the strikes page on the character sheet, if that matters.

A toggle at the top of the Strikes tab, or a separate tab for weapons would also work for my purposes.

**Comment by Drental** [comment]
I don't actually list weapons. I list strikes as the system lists them.

you can reach the equip button by going to the inventory tab, rightclicking the weapon, and then toggling the equipped state on the item sheet (I think there's a toggle for that anyway.)
