### ISSUE TITLE
Feature Request: Different positions for "Enable hover" option

### ISSUE THREAD

**Issue by weepingminotaur** [Drental/fvtt-tokenactionhud#106]
Feature request for Token Action HUD: the ability to change the position when the "Enable hovering" option is on. Currently, if you enable hovering, it always appears to the right of the token, which means that items sometimes fall "off" the screen. Would be great if we had options to have it appear on top, at the bottom, or the left.

**Comment by Larkinabout** [comment]
Feature developments are moving over to [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core), however I'm unlikely to support the 'Enable hovering' feature going forwards as it doesn't suit the current format of Token Action HUD. It might be better placed with other modules like Ripper's Macro Wheel, which displays small buttons around the selected token.
