### ISSUE TITLE
Action tracker

### ISSUE THREAD

**Issue by Orionox** [Drental/fvtt-tokenactionhud#107]
Would be nice if there was an optional little HUD element that tracked the # of actions/bonus actions/reactions used. Like anytime I clicked on a weapon it would increment up the actions, anytime I used a bonus actions spell it would increment up the bonus action counter and would reset at the beggining of a turn for actions and a round for reactions. Or have a manual reset button.

**Comment by Drental** [comment]
This is not in the scope of this module for two reasons
1) I have no place to display that information.
2) depending on used modules clicking an action can be an action, or just provide information to the other players or GM.

**Comment by Orionox** [comment]
I figured you'd just put a number over the already existing hud elements, like that one module that adds numbers over conditions.  thank you for responding regardless.
