### ISSUE TITLE
Skill names not being localized (for PF2)

### ISSUE THREAD

**Issue by DalvynPF** [Drental/fvtt-tokenactionhud#108]
It looks like the skill names are not being localized in TAH :

![image](https://user-images.githubusercontent.com/66378495/139465601-c667184b-bcce-4b1e-bbfc-61d8ea5b447f.png)

Thanks!

**Comment by Drental** [comment]
Should be fixed now, can you test?

**Comment by DalvynPF** [comment]
Confirmed working.

Thank you for the fix !
