### ISSUE TITLE
PF2e - can't pop out chat card for spells cast through the HUD

### ISSUE THREAD

**Issue by shemetz** [Drental/fvtt-tokenactionhud#110]
In the Pathfinder 2e system, Foundry 0.8.9, when I cast a spell through the hud:

![image](https://user-images.githubusercontent.com/6516621/140029309-bbcd1628-df45-45f8-b55a-f7bc628204ec.png)

it creates the following chat card, which can be right-clicked...

![image](https://user-images.githubusercontent.com/6516621/140029370-ac6dc71e-db56-4f88-87c1-0060f3327476.png)

And the **Pop-Out Message** option does not work.

When clicking it nothing happens and I get a console error:

![image](https://user-images.githubusercontent.com/6516621/140029622-3da4afbb-aed9-4779-b4f0-4faf700013a4.png)

From these lines of foundry.js code:

![image](https://user-images.githubusercontent.com/6516621/140029658-70588166-d1f3-4380-baf6-2391e2f11c40.png)

Note that the chat card **does** allow popping it out if it's cast from the character sheet.

After investigating I found out that the difference between these two cases is that the ChatSpeakerData (`data.speaker` field) in the two messages are different.  Specifically, the chat message created by Token Action HUD has `alias: undefined, scene: null`, compared to a normal message which has e.g. `alias: "Ezren", scene: "ubUcW9srPIsJ2ZqW"`.

So the bug is probably that the speaker alias field is not getting filled here.  I'm not sure if the way to solve this bug is through a change in the Token Action HUD module, the PF2e system, or the Foundry codebase, but I thought this would be the best place to report it.

**Comment by Larkinabout** [comment]
Closing as tested as working in Foundry VTT v10.286, Pathfinder 2nd Edition v4.1.3 and Token Action HUD v3.0.10. Let me know if this issue still exists for you on the latest release.
