### ISSUE TITLE
Add Support: 2D20 Star Trek, Conan, Fallout

### ISSUE THREAD

**Issue by Ryach** [Drental/fvtt-tokenactionhud#111]

**Comment by Drental** [comment]
is that one system or three?

**Comment by Ryach** [comment]
2D20 is system mechanic which have different versions. For now are there main versions of 2d20 but so far I know they are simple, and every of them are made from Conan base

**Comment by Drental** [comment]
at the current time I have no intention to add support for additional systems. Closing to get a better overview of the state of the module.
