### ISSUE TITLE
Support clearing DFreds Convenient Effects from Token Action HUD

### ISSUE THREAD

**Issue by TaakoMagnusen** [Drental/fvtt-tokenactionhud#113]
[DFred's Convenient Effects](https://github.com/DFreds/dfreds-convenient-effects) is super powerful and super popular. Many people use it to replace the default conditions and add effects to their tokens.

I noticed that when you apply a non-condition Convenient Effect (such as a lantern or the blur spell) to a token the Token Action HUD successfully displays it, but when clicking on the effect to remove it it does not remove it.

I'm not sure if this is caused by Convenient Effects of Token Action HUD since i'm not sure how those HUD buttons work to clear the condition effects (which work to clear the Condition Effects provided by Convenient Effects), but it would be nice if it could call the clear on all convenient effects

**Comment by MarkeyMarke** [comment]
I am bumping this as well! I love both of these modules.

**Comment by Larkinabout** [comment]
Added in release 3.0.5.
