### ISSUE TITLE
Support for Cyberpun Red System

### ISSUE THREAD

**Issue by Dadrak** [Drental/fvtt-tokenactionhud#116]
**Description**

Support for the Cyberpunk Red game System on FoundryVTT. Token action Hud would give the player and Game Master a more accessible fast paced and immersive game, without the need to open the character sheet in combat and narrative based scenarios.

Here is the systems FoundryVTT page : https://foundryvtt.com/packages/cyberpunk-red-core

Here is the systems Gitlab page : https://gitlab.com/JasonAlanTerry/fvtt-cyberpunk-red-core

Also I did make the same request on their Gitlab, a dev has started to integrating it, you can find his progress here : https://gitlab.com/JasonAlanTerry/fvtt-cyberpunk-red-core/-/issues/344

As always thank you for your hard work and I wish you a good day

**Comment by flynnkd** [comment]
Bump :)

**Comment by Drental** [comment]
at the current time I have no intention to add support for additional systems. Closing to get a better overview of the state of the module.
If someone made a PR I'd likely merge it and release it.
