### ISSUE TITLE
[5e] Group ability checks with skills

### ISSUE THREAD

**Issue by weepingminotaur** [Drental/fvtt-tokenactionhud#117]
Right now, you can either have ability checks (STR, CON, etc.) grouped on their own, or with saving throws. Logically, they are checks, just like "skill" checks, and should be grouped with Acrobatics, Athletics, and so forth. Grouping all checks together would reduce clutter by eliminating one menu category from the HUD.

**Comment by Larkinabout** [comment]
An extension of the 'Show separate ability check and save categories' setting to allow users to pick might be preferable as I can see other users prefering the current split.

- Attributes
  -  Abilities
  -  Skills

**or**

- Attributes
  - Checks
  -  Saves
  -  Skills

**or**

- Abilities
- Skills

**or**

- Checks
- Saves
- Skills

**Comment by Larkinabout** [comment]
[Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core) and [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e) now have this feature baked in with customisable subcategories.
