### ISSUE TITLE
[Feature Request] Include Death Saves in the utility tab for DnD5e Systems

### ISSUE THREAD

**Issue by MarkeyMarke** [Drental/fvtt-tokenactionhud#118]
I find that I have to add Death Saves to the Token Action HUD manually for myself and other players for DnD5e systems; is it possible to just have it by default for everyone?

**Comment by Drental** [comment]
![image](https://user-images.githubusercontent.com/74384067/142942956-07451228-455d-437c-aa26-89cad6a3eb91.png)
I see it on PC tokens that are at zero HP. should that logic change?

**Comment by MarkeyMarke** [comment]
Ah! I didn't realize this. That works completely fine.
