### ISSUE TITLE
Feature Request: SWADE: Display Special Abilities 

### ISSUE THREAD

**Issue by JasonSK22** [Drental/fvtt-tokenactionhud#120]
Is there a way to display Special Abilities from an Actor Sheet in the HUD like edges/hindrances?  Can this be added?

**Comment by Drental** [comment]
![image](https://user-images.githubusercontent.com/74384067/143722812-e26a736a-68ec-4875-82e6-fa7c57ff7bc7.png)

wait, you mean special abilities not edges/hindrances...

should those go to a new group and do they have anything to roll usually?

**Comment by JasonSK22** [comment]
> wait, you mean special abilities not edges/hindrances...
*Having Special Abilities in a list like Edges/Hindrances would be great

> should those go to a new group and do they have anything to roll usually?
*A new group is good!  Some times a SA will have an AE but that's about it.

For me as a GM its more about not forgetting which SA a creature has and being able to flow the SA description to the Chat.

**Comment by Drental** [comment]
closed with release 1.3.28
