### ISSUE TITLE
[Feature request] Add a hook for retrieve the result detail of the roll launched with Token Action Hud

### ISSUE THREAD

**Issue by p4535992** [Drental/fvtt-tokenactionhud#123]
In these days I found myself developing a multisystem module, not wanting to rewrite the wheel for the rolls I used your requestHandler api to manage requests as a dependency, but now I find myself with the need to find the result.

It is possible to add a Hook from which I can retrieve data such as the token, the roll element (save, skill, item, result, total, etc.) in a similar way to how it was managed by the _Monk Token Bar module_ with its `Hooks.callAll ( 'tokenBarUpdateRoll', this, message, update.id, msgtoken.roll); ` ?

I would also be happy to try to prepare a PR if you give me some indication of how you would like the code to be set.

**Comment by Drental** [comment]
ping me on this on the weekend please, I am about to have so much excitement (first online convention, GMing 3 games in 2 days) that I will forget everything.

Sorry for the inconvenience.

**Comment by ravingdragoon** [comment]
Any news on this feature? The new module p4535992 is making is really cool, and the added functionality with this mod would make it even cooler.

**Comment by Drental** [comment]
oh, I haven't looked into this, I was on a convention when the request came in and quite literally forgot all that happened outside of the games.

so what's that roll hook? I am not sure I can make that in a generic way from looking at it, but I want to know more about it now.

**Comment by p4535992** [comment]
The use case is the following I invoke the requestHandler class by code passing it the information it requests and it works! The extra thing is that I need to read the roll result and / or the information on it.

and yea is not simple (at least for me), for now i'm trying to replicate  the work of Monk Token Bar with his api where i can retrieve the roll details and pass some custom info on the flags with all the information i need.

**Comment by Drental** [comment]
after thinking it over I believe this is out of scope for me to do.
I could do it for one system maybe, but even then it's basically writing a new handler and I don't even know how to supply the Hook.
If you want to make a PR that shows it off in one handler for a system I'll try to do it for the whole system. It's one of the things where this module only having a maintainer and no dev is kind of sad :(
