### ISSUE TITLE
[Swade] When using dice-so-nice, two bennies are thrown instead of one when clicked from TAH

### ISSUE THREAD

**Issue by Wigginns** [Drental/fvtt-tokenactionhud#125]
When using the dice-so-nice module spending a benny will result in two being thrown because dice-so-nice already throws one when you spend a benny.

Playing around with the minified JS, removing the `_showDiceBenny()` calls from the rollHandlers results in a single benny being thrown instead of multiple.

https://github.com/Drental/fvtt-tokenactionhud/blob/b41e194c6e59467b3089dbfa0c0122488d1b8cac/scripts/rollHandlers/swade/swade-br2sw.js#L174-L175

https://github.com/Drental/fvtt-tokenactionhud/blob/b41e194c6e59467b3089dbfa0c0122488d1b8cac/scripts/rollHandlers/swade/swade-base.js#L132-L133

**Comment by Drental** [comment]
> Playing around with the minified JS

Mad respect for that. will fix.

**Comment by Drental** [comment]
fixed in 2.0.4

**Comment by Wigginns** [comment]
> > Playing around with the minified JS
> 
> 
> 
> Mad respect for that. will fix.

Wasn't bad tbh. It's all just compact, none of the symbols or names change 😆
