### ISSUE TITLE
[Feature Request:] Hide From Players Option?

### ISSUE THREAD

**Issue by Evanramsey** [Drental/fvtt-tokenactionhud#126]
Any way you can add a hide from players feature. I've noticed that some new players have trouble with VTT controls and it fill up the space of the screen. To some players, it seems more of an annoyance to them but for me, it helps speed up so much of the game.

**Comment by Drental** [comment]
This is literally the first option in the module settings. Players that want to hide the HUD must do so themselves unless you use a module to force settings for the players.
