### ISSUE TITLE
Cannot Update Token Action HUD

### ISSUE THREAD

**Issue by shirizaan** [Drental/fvtt-tokenactionhud#127]
Foundry VTT 0.9 gives the following error when checking for updates:

> The request to https://github.com/Drental/fvtt-tokenactionhud/releases/latest/download/module.json did not provide a valid manifest file.

**Comment by Drental** [comment]
That looks like a foundry issue since that module json has already been successfully downloaded by others. Can you retry in a bit and check if it fails again?

**Comment by shirizaan** [comment]
Looks like it is working again. Thanks for checking. This can be closed.
