### ISSUE TITLE
Position shifts after repositioning

### ISSUE THREAD

**Issue by Weissrolf** [Drental/fvtt-tokenactionhud#129]
Hello.

When I reposition the HUD then selecting another token (as GM) or using a toggle (PF2) shifts the HUD a few pixels to the lower right. After that initial shift no more shifts seem to happen until the HUD is repositioned again. So the current workaround is to position the HUD a few pixels to the upper left and then let that initial shift happen, which is a bit inconvenient.

v9, PF2 v3

**Comment by Larkinabout** [comment]
Fixed in release 3.0.5.

**Comment by Weissrolf** [comment]
Great, thanks! :-)
