### ISSUE TITLE
spells other than cantrips do not show

### ISSUE THREAD

**Issue by gioppoluca** [Drental/fvtt-tokenactionhud#132]
On V9 only cantrips are visible all other levels are not.

**Comment by Drental** [comment]
Which system is this about?

**Comment by gioppoluca** [comment]
5 edition

**Comment by gioppoluca** [comment]
I'm on version 2.0.9 with foundry v9 and 1.5.6 of 5e do you need other modules that could generate quirks?

**Comment by Drental** [comment]
probably an export from the character because I am sure it works for most people

**Comment by Drental** [comment]
![image](https://user-images.githubusercontent.com/74384067/148280804-3a981d5f-a565-49df-8e39-a518642a9f6e.png)

**Comment by brandonhinds** [comment]
@gioppoluca Are the spells prepared? I had that problem just now.

**Comment by Larkinabout** [comment]
Closing as answered by @brandonhinds.
