### ISSUE TITLE
Error using SWADE  and it is set to BR2

### ISSUE THREAD

**Issue by grendel111111** [Drental/fvtt-tokenactionhud#137]
If the Token action HUD is set for Better Rolls 2 then when you change the status through the HUD it applies the icon twice.
![image](https://user-images.githubusercontent.com/80164119/148685985-55a70977-06e0-4c80-b215-7bb3d853c6fa.png)

If it is set to default SWADE then it only shows the icon once.
![image](https://user-images.githubusercontent.com/80164119/148686007-3cd04cab-cc7c-41cf-ab81-7ce211c56c50.png)
![image](https://user-images.githubusercontent.com/80164119/148686028-27349f51-d9e8-43ab-8d71-5080e7206c8e.png)

**Comment by bloy** [comment]
@Drental I am pretty sure that this will also be fixed by #160

**Comment by Larkinabout** [comment]
Tested as working in release 3.0.6.
