### ISSUE TITLE
PF1E - Allow Fast-forwarding rolls and skills showing

### ISSUE THREAD

**Issue by Fair-Strides** [Drental/fvtt-tokenactionhud#138]
I've noticed two things recently that differ between Token Action HUD and the PF1E character sheets.

A user can hold the Shift key when clicking on something (an attack, skill, .etc) to fast forward a roll, skipping the pop-up dialog by adding `fastForward: true` to the roll call. Though, there's a system setting to invert this behavior (if Shift is **not** held, fastForward = true).

Also, each skill has a checkbox and boolean for "Always show". Even when I had this set, the skill wouldn't show up in Token Action HUD, so I'm not sure how it determines whether to show a skill. It shows several non-ranked skills by default.

**Comment by Larkinabout** [comment]
I have checked on Foundry VTT v10.286, Pathfiinder 1 v0.82.2 and Token Action HUD 3.0.8, but cannot see an "Always show" checkbox for skills. Skills will only appear on the HUD where the Requires Training checkbox is not ticked.

**Comment by Larkinabout** [comment]
Skipping dialogs when using the shift key added in 3.0.9.
