### ISSUE TITLE
[SFRPG] Option for Weapon Actions to Attack Rather Than Create Chat Card

### ISSUE THREAD

**Issue by Tarbarian** [Drental/fvtt-tokenactionhud#141]
Currently, using a weapon action within the equipment category creates a card for the weapon, which you can then use to attack or roll damage. An option to have one of those two actions taken immediately would be useful, either by having it as an option in the module setting or by allowing different clicks to do different things (normal click continues to create the card, shift+click rolls an attack, ctrl+click rolls damage).

![image](https://user-images.githubusercontent.com/76751079/149211424-fdcd09cd-1db4-4548-883b-17e6b6f04b79.png)

Thank you!

**Comment by Larkinabout** [comment]
Added in release 3.0.10.
