### ISSUE TITLE
Token Action HUD not working for character sheets in sw5e

### ISSUE THREAD

**Issue by Zgames727** [Drental/fvtt-tokenactionhud#144]
After the Foundry V9 update, token action HUD doesn't seem to be working for most sheets. It isn't working for any character sheets and isn't working for custom NPCs. However, it does seem to be working for all vehicles as well as NPCs/monsters from the compendium.

**Comment by MatteoPieroni** [comment]
There is something not working for me as well.

While that is being investigated I have used the second last update and it works fine: https://github.com/Drental/fvtt-tokenactionhud/releases/download/2.0.11/module.json (you can find this file in release 2.0.11 in the releases page).

**Comment by Drental** [comment]
should be fixed with recent update
