### ISSUE TITLE
DnD3.5e, Psionic powers (spells) not showing in Spells button on token hud

### ISSUE THREAD

**Issue by BlackWand1** [Drental/fvtt-tokenactionhud#145]
Hey!

If you configure your character as a psionic (Spellcasting type: Psionic), that "Spells" token hud button is empty.
Would it be possible to get it to list the powers just like spells for wizard?

Has been this for as long as I used Foundry (v8+9)
System: 3.5e SRD

Cheers

**Comment by BlackWand1** [comment]
Hey, do you want some more input for this?

![image](https://user-images.githubusercontent.com/85252943/153264822-e305e16f-cb4e-4a03-9a93-d1af0b592e7c.png)

**Comment by Larkinabout** [comment]
Blocked as awaiting system update to Foundry VTT v10.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.13.
