### ISSUE TITLE
Token Action HUD does not roll dice.

### ISSUE THREAD

**Issue by relaytheory** [Drental/fvtt-tokenactionhud#153]
![Screenshot_5](https://user-images.githubusercontent.com/32248765/152443718-2cd083a7-e7ec-45b4-9cf5-4e0fa93b8f84.png)

Module was ran by itself using VTT build 249.
Module version 2.1.3
Forge VTT was used as server host.

**Comment by Drental** [comment]
Known issue fixed in 2.1.3
