### ISSUE TITLE
System Request: toolkit13 (13th Age)

### ISSUE THREAD

**Issue by tbrockwood** [Drental/fvtt-tokenactionhud#154]
Would it be possible to get Toolkit13 added to supported systems? Even for basic stuff, like the core Melee Attack and Ranged Attack?

**Comment by Drental** [comment]
could be, easiest way to get that is do like the Earthdawn4e system and do a PR for the new system :)
I'm already overwhelmed with *just* doing the support for already released parts, so I won't take this on by myself anytime soon :(
