### ISSUE TITLE
Error with Features and Token Action HUD, DnD4e

### ISSUE THREAD

**Issue by PaperMonkeyLord** [Drental/fvtt-tokenactionhud#156]
Getting this error whenever I try and click a feature from the tokenactionhud.
![image](https://user-images.githubusercontent.com/95109274/152702176-1b27a45b-11fa-4060-82ec-436d2426dc75.png)

**Comment by Drental** [comment]
- Draconas seems to be aware.
I'll wait a bit for a PR, then maybe tackle this.
