### ISSUE TITLE
Request: Change "Toggle Visibility" to "Toggle Hidden"

### ISSUE THREAD

**Issue by shemetz** [Drental/fvtt-tokenactionhud#157]
![image](https://user-images.githubusercontent.com/6516621/152771207-9fb89505-7eea-47cf-965b-107eccc0252f.png)

The name of this HUD button is confusing.  When marked red (i.e. enabled), it implies something is unusual and specifically changed about the token.  However, currently being marked red means it's visible, which is the default behavior for tokens.

I would like it to instead say "Toggle Hidden" (or just "Hidden"), and have the button marked as red when the token is **hidden**.

**Comment by Larkinabout** [comment]
Added in release 3.0.5.
