### ISSUE TITLE
its not working in PF1

### ISSUE THREAD

**Issue by southwind987** [Drental/fvtt-tokenactionhud#161]
I play PF1. Recently updated Fvtt to V9 build249, and pathfinder1 to 0.80.9 Since then, the HUD has not appeared when we click on a token. The module is active.i creat a new world is not use . Hope to solve the issue as your module is invaluable. Please let me know if you need more information.
![1](https://user-images.githubusercontent.com/99687418/153935844-d40733b2-09d6-4507-9cf0-0029d7c1b9d2.png)
![2](https://user-images.githubusercontent.com/99687418/153935863-8e7ff29e-7b27-4311-a4d3-5659d1e368bc.png)
![3](https://user-images.githubusercontent.com/99687418/153935876-5c933574-fceb-473b-b558-7e2e1b579e05.png)

**Comment by Drental** [comment]
Delete the module, make sure the folder is gone and install it again. See if that helps.

**Comment by southwind987** [comment]
its useful ,thank you!!!
