### ISSUE TITLE
[Performance] Token stutters when moving it around scene if modules with additional GUI are loaded and visible

### ISSUE THREAD

**Issue by Hargrim** [Drental/fvtt-tokenactionhud#165]
Hi,

I encountered this issue when using Token Action HUD and SmallTime and / or Always HP. Basically the token lags if there are any other GUI elements loaded in the world. I recorded a video using Always HP because it got a button to turn it on and turn it off to better illustrate the issue.

I'm using latest versions of the modules.

What I found out so far:

- Doesn't seem to be related to the power of client - I run it on my main PC and on low end laptop and behavior was similar
- Doesn't seem to be related to the number of cores on the VM - same behavior on 1, 2, 4 and 8 cores

Exact behavior: https://webm.red/view/pwDV.webm

![image](https://user-images.githubusercontent.com/16460565/155108928-3f1172ea-3de6-4853-b917-2c4277d6d114.png)

**Comment by Hargrim** [comment]
I updated to 9.251 today and the issue is still there.

I also noticed that there is a lag after clicking the token before the HUD shows - there is like 0.5-1s freeze of the Foundry before everything goes back to normal. This happen only when additional GUI elements are enabled (both examples from my initial report can be used to test this).

**Comment by Larkinabout** [comment]
Performance improvements will continue with [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core).
