### ISSUE TITLE
SWADE add run.

### ISSUE THREAD

**Issue by grendel111111** [Drental/fvtt-tokenactionhud#173]
Is it possible to add the run action under the utility category? It seems to be the only regularly used action you can't do from the HUD.
![image](https://user-images.githubusercontent.com/80164119/156868869-93a2d554-7354-49a7-82ef-69e7db9f4da8.png)

**Comment by Larkinabout** [comment]
Awaiting actor function in next SWADE release.

**Comment by Larkinabout** [comment]
Added in release 3.0.14.

**Comment by grendel111111** [comment]
Sorry,  but can I make a suggestion. It is saying run macro, because it is a macro for running. Can it just say run. Otherwise people will press it if they want to run "any" macro.

**Comment by Larkinabout** [comment]
I'm not sure we're looking at the same thing? It should say 'Running Die', not 'Run Macro': 
![image](https://user-images.githubusercontent.com/105953297/201231929-9ab23c70-15a5-41c9-94d7-d56276d7336b.png)

**Comment by grendel111111** [comment]
You're right I was looking at it under utility menu. There is a run macro,
which does the same thing.[image: image.png]
