### ISSUE TITLE
System Support Request: SW5e (Star Wars Fifth Edition)

### ISSUE THREAD

**Issue by TogaParty** [Drental/fvtt-tokenactionhud#180]
Built on D&D 5e, this mostly seems to work as is, except that actionable features don't appear.

**Comment by unrealkakeman89** [comment]
The class features used to show up,  but after an update awhile back thru disappeared from the bar.

**Comment by unrealkakeman89** [comment]
I tried to make a pull request but for some reason, it did not go through so I am attaching a .zip of the files. They have the following changes:
**en.json**
- added `tokenactionhud.atwill`

**sw5e-actions.js**
- brought into line with DND5E
- added `Class Feats` section

**sw5e-actions-by-type.js
- brought into line with DND5E

[TAHSW5E.zip](https://github.com/Drental/fvtt-tokenactionhud/files/9337626/TAHSW5E.zip)

**Comment by Drental** [comment]
I think this can be closed now.
