### ISSUE TITLE
[Bug] PF2e Rest for the Night erroring

### ISSUE THREAD

**Issue by meldogs** [Drental/fvtt-tokenactionhud#181]
Foundry Version 9.255
PF2e Version 3.7.1.10801

Players get this error when trying to use it.
![error](https://user-images.githubusercontent.com/71352952/158210349-7f422342-f154-4784-97a7-010d86b2bf0b.PNG)

**Comment by timingila** [comment]
One game I'm in, two characters get this error and three characters do not.

It's all moot though, since "Rest for the Night" is built into the PF2 character sheet now via the "person in a bed" icon under Max HP. I wonder if the option can be removed from the utility menu for PF2?

**Comment by meldogs** [comment]
This is exactly what the player did that ran into the issue. Removing it should be ok I would think.

**Comment by Drental** [comment]
fixed in PF2e 3.8.x
