### ISSUE TITLE
Spells from the Magic Items mod do not show in TAH

### ISSUE THREAD

**Issue by Zamrod** [Drental/fvtt-tokenactionhud#188]
These used to work but it appears they no longer show up in the TAH at all.

**Comment by Zamrod** [comment]
After some more testing, it looks like spells that are on an item no longer show up in the TAH unless the base item has an action set on it. So for a Wand of Magic Missiles, the Magic Missile doesn't show up in the list unless the wand has an action type. Which makes the wand show up in the list of actions you can take even though the wand doesn't have any abilities by itself.

Also, unless I'm misremembering, spells from Magic Items used to show up in the Spells list and they don't anymore.

**Comment by Drental** [comment]
will be fixed in 2.2.12
