### ISSUE TITLE
You are referencing Actor#getOwnedItem(itemId) warning 

### ISSUE THREAD

**Issue by thatlonelybugbear** [Drental/fvtt-tokenactionhud#19]
`foundry.js:12448 You are referencing Actor#getOwnedItem(itemId) which is deprecated in favor of Actor#items#get(itemId). Support will be removed in 0.9.0`

Lines 824 and 835 in dnd5e-actions.js

It might be a good idea for down the line compatibility to change the:
`let target = actor.getOwnedItem(consumeId);`
to
`let target = actor.items.get(consumeId);`

Also line 15 in rollHandler.js

**Comment by Drental** [comment]
feexed
