### ISSUE TITLE
Token Action HUD Not Showing All NPC's Spells (5e)

### ISSUE THREAD

**Issue by King-Khufu** [Drental/fvtt-tokenactionhud#191]
I cannot get Token Action HUD to show all of the spells that NPC Actors have on them. I use the Character Action List module.

![image](https://user-images.githubusercontent.com/87103761/160967604-e45c5909-712a-4d95-8f22-9aef7f02605a.png)

**Comment by Drental** [comment]
can you export the actor and link it in the ticket?

**Comment by Larkinabout** [comment]
I'm unable to reproduce this issue on Token Action HUD 3.0.4 andCharacter Actions List dnd5e 6.0.1. Does this issue still exist?

**Comment by Larkinabout** [comment]
Closing as unable to reproduce in the latest release. Let me know if it's still an issue.
