### ISSUE TITLE
Support for SPACE 1889 System

### ISSUE THREAD

**Issue by Scepfari** [Drental/fvtt-tokenactionhud#194]
@Drental: I'm working on the implementation of SPACE 1889 for FVTT and don't want to reinvent the wheel, especially if Token Action HUD provides the functionality I'm looking for.
 So I took a closer look and added HUD support for Space 1889 on my machine. It was actually as easy as you said. Great praise. Can I just start a pull request, or do I have to do something else? 
  
Here is the system page : https://github.com/Scepfari/SPACE1889-FVTT

**Comment by Drental** [comment]
go ahead! I will merge it as soon as it is done :)
