### ISSUE TITLE
Feature Request: Group Rolls

### ISSUE THREAD

**Issue by Deadlander** [Drental/fvtt-tokenactionhud#199]
Adding a group roll function for would be super useful for helping to speed up combat.
i.e.: In my SWADE games, being able to select a group of Mooks, have them target a character, and then clicking the attack button would trigger them all to make an attack roll, rather than having to roll for each individually.

**Comment by apoapostolov** [comment]
@Deadlander you can already do this, if TokenHUD would allow to add macros to the tabs (I think it can). Use the mod Monk's TokeBar and use the Tokenbar to create Group Rolls (pubic or hidden, etc.) for specific attributes or skills. TokenBar lets you create macros of the rolls templates, such as GMRoll of Perception for all Players. Then you can add these macros to Token HUD.

**Comment by Larkinabout** [comment]
If a roll handler module out there does this, Token Action HUD can support the roll handler, otherwise you can set up macros as suggested. In either case, support for new features is moving over to [Token Action HUD Core](https://github.com/Larkinabout/fvtt-token-action-hud-core/).
