### ISSUE TITLE
Starfinder - Starship crew commands not showing in Action hud

### ISSUE THREAD

**Issue by Vallant85** [Drental/fvtt-tokenactionhud#201]
When adding players to the crew section on the starfinder starship sheet, the Action hud is not showing the different commands for each role. This works for NPC sheets and sometimes, only the magic officer is shown on players action hud, even when no magic officer is assigned. Im pretty sure this has worked in the past.
Will attach a screenshots
Pic 1 - No crew added, Magic officer still showing
Pic 2 - All crew added, only magic officer showing
pic 3 - NPC crew working as intended
![Pic 1](https://user-images.githubusercontent.com/98958424/164051018-cc04df0b-6e8e-43f0-8b4d-b6ba89e9ce7e.png)
![Pic 2](https://user-images.githubusercontent.com/98958424/164051029-17423483-c94a-49e5-857e-2ef14d7c822e.png)
![Pic 3](https://user-images.githubusercontent.com/98958424/164051032-5bdba9f8-0cd5-4e2c-93a0-e3eaeeebb180.png)

**Comment by themockster** [comment]
Hello, any updates on this? 

We faced the same issue last night. It worked fine before, but now it does not. 

Whenever we have a player-owned ship, crew actions don't show up based on assigned role.

**Comment by Larkinabout** [comment]
Waiting on a release of the Starfinder system for Foundry VTT v10.

**Comment by Larkinabout** [comment]
foundryvtt-starfinder/foundryvtt-starfinder#747

**Comment by Larkinabout** [comment]
Fixed in release 3.0.14.
