### ISSUE TITLE
HUD does not respect sort value of character sheet.

### ISSUE THREAD

**Issue by MontyLFP** [Drental/fvtt-tokenactionhud#203]
My players wish to reorganize their HUD for readability and ease of use, and expect it to reflect the order of their character sheets which can be organized. Instead, it apparently always sorts by age and not sort value.
![unknown](https://user-images.githubusercontent.com/7494262/165868987-1575a475-cb01-497e-9798-858168efead7.png)
It should respect the sort value to mimic character sheet behavior.

This rolls in a lot of customization with minimal work to implement.

**Comment by Drental** [comment]
I am but a mere maintainer, not an active developer, and the number of systems (and the by system basis of the sort value bing present, I'll accept if you say most, but it's not all) makes a general change like this time consuming and tedious to do.
if you name a specific system I can see what I can do - but honestly I'm searching for someone else to keep maintaining or even developing the module further.

**Comment by Larkinabout** [comment]
If this is for D&D 5e, I've checked in release 3.0.4 and inventory is sorted in the HUD based on the order on the character sheet.

**Comment by Larkinabout** [comment]
Tested as working in 3.0.4+.
