### ISSUE TITLE
HUD is not displaying correctly, renderin gt he module useless...

### ISSUE THREAD

**Issue by ChrisLondon44** [Drental/fvtt-tokenactionhud#206]
Since the last update, the HUD is acting very weirdly in Savage Worlds to the point it's useless (see pic). I've tried deactivating the latest modules i've installed in vain. It really started with the last Token HUD update...
![Issue](https://user-images.githubusercontent.com/104872690/166588071-7882e05b-7a8c-409c-8b69-531e40eb91f8.png)

**Comment by bduffy02** [comment]
I am also having this issue. using TAH version 2.2.15 with Foundryvtt Version 9 - Build 269. running pathfinder 1e version 0.80.20

**Comment by ChrisLondon44** [comment]
No. It may have happened after the Foundry v9 update. Not sure. I've tried to uninstall Token Action HUD, quit Foundry, relaunch Foundry and re_intall the module but it still doesn't work. Lakes sense that this is a CSS issue...

**Comment by ChrisLondon44** [comment]
You're a genius!!! The solution is effectively to unistall the module, delete the actual token-action-hud module folder in AppData\Local\FoundryVTT\Data\Modules and reinstall the module... Thank you so much!!!
