### ISSUE TITLE
PF2E switch Spells from Posting to Chat to Casting

### ISSUE THREAD

**Issue by apoapostolov** [Drental/fvtt-tokenactionhud#219]
This is going to solve a lot of problems with new players who use the spells and forget that they didn't use the slot at all, but just posted it to chat, and this causes problems in the long run forgetting how many times they cast using the same slot. This is especially egregious with 5E players making their transition to PF2. 

Currently, all spell items use Post to Chat. Switching to the Cast function will remove the need to have [-] buttons to remove the slots. This will also solve #217 at least partially (still would be great to display the uses).

**Comment by apoapostolov** [comment]
Right click on the spell and then Send to Chat from the header.

**Comment by JerkyGunner** [comment]
Using the module Item to Chat makes that possible, thanks for the heads up.

I still think a built-in setting to allow the GM to choose how they would like the click to work would be a nice option to have. No need to remove one or the other, if at all possible.

**Comment by apoapostolov** [comment]
This is possible to do now with PF2 Workbench for both npcs and players.

**Comment by Larkinabout** [comment]
Thanks for the update.

**Comment by JerkyGunner** [comment]
> This is possible to do now with PF2 Workbench for both npcs and players. This can be closed.

Can you tell me how to do this? Don't want to reopen but not sure where the setting for this is in the Workbench,
