### ISSUE TITLE
PF2E (maybe other) Block use of Bomb with no unit left

### ISSUE THREAD

**Issue by uniwars** [Drental/fvtt-tokenactionhud#223]
Hello, with the PF2E alchemist can craft daily bombs that are added to their inventory and deleted after a rest
Daily bombs are consummables weapons but doesn't disappear when reaching "0" quantity in the inventory, but un the sheet the "strike" action is blocked when there is no bomb of that type left

in TAH the strike button is not blocked when quantity is "0", so player using TAH might forget to count how many bombs they have left if they doesn't open their sheet to check

I don't know if it is possible but removing the bomb entry in TAH when there is no quantity left or blocking the strike with an error message would be neat.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.5.
