### ISSUE TITLE
Strange Module Behavior

### ISSUE THREAD

**Issue by comsnath** [Drental/fvtt-tokenactionhud#225]
Running the following version:
![image](https://user-images.githubusercontent.com/60007620/174003649-78240dd3-20cb-490e-931b-89b015f5c2b8.png)
I tested it with and without any other modules, but the issue persists.
![image](https://user-images.githubusercontent.com/60007620/174003742-819bc1f2-e24c-4141-90b0-68abb7cad45c.png)
The module is on version 2.2.17.

**Comment by Drental** [comment]
this is just a broken download, uninstall and re-install again until it works.

CSS File is not loading properly
