### ISSUE TITLE
Strange rendering issue

### ISSUE THREAD

**Issue by l-pogson** [Drental/fvtt-tokenactionhud#228]
I was really loving Token Action Hud until I weirdly started having an issue with it. It's not rendering properly as you can see... This is what happens after clicking on the bug bear.
![image](https://user-images.githubusercontent.com/10415210/174439127-84e4ad00-b9ed-4da5-b3b0-cbef6ee32925.png)
Then, when you hover over any of the actions, this happens:
![image](https://user-images.githubusercontent.com/10415210/174438993-ff24c8bf-d42a-42c8-a199-a7e8a6818c91.png)
I've tried disabling all modules except TAH, installing older versions(then upgrading), messing with TAH settings, using different browsers, the native Foundry application, system restart, all the same issue.

**Comment by Drental** [comment]
uninstall and re-install the module.
it's downloaded incomplete and is missing the CSS for some reason.
apparently the size of the module makes this specific issue more likely, sorry I can't do anything about the root cause. but I know uninstalling and reinstaalling will fix this.

**Comment by l-pogson** [comment]
Brilliant! Thankyou so much.
I had tried uninstalling and reinstalling, but this time I checked the modules folder and it was still there! 
Delete, reinstall, working perfectly now.
Also used this trick to fix another module which mysteriously stopped working.
