### ISSUE TITLE
Token Action HUD does not display with new Token with a base class in PF1e

### ISSUE THREAD

**Issue by Golldan1111** [Drental/fvtt-tokenactionhud#229]
If you create a new PC Token with a base Class and bring to a Scene, it does not display TAH. If you create without a Class, it works.
V9 bld 269 PF1e 0.81.0
![ScreenHunter 370](https://user-images.githubusercontent.com/86072213/174458249-d8a7fb7b-83db-48e9-b219-94362a2617a9.jpg)
Issue
![image](https://user-images.githubusercontent.com/86072213/174458286-7680830c-952c-4112-a39f-3c3a485e6d8d.png)

**Comment by apflu** [comment]
i've experience this too(but in bright chrome theme)
![image](https://user-images.githubusercontent.com/25970844/175393221-0a52c059-a9e3-4953-89d9-e49df05df1b5.png)

**Comment by haloa92** [comment]
I too seem to have this issue

**Comment by dmrickey** [comment]
It looks like the issue is here. 
![image](https://user-images.githubusercontent.com/3664822/176255600-93075a05-6953-44bc-acd3-2a8002180c10.png)

This has been moved into PF1's subactions

**Comment by ckdragons** [comment]
It would seem that one of my players have also encountered this issue with his cleric actor.
