### ISSUE TITLE
PF2e - Strike section 

### ISSUE THREAD

**Issue by arglez** [Drental/fvtt-tokenactionhud#23]
When a character is updated with a Effect example montain stance. The strike section does not show the strike give it by the stance until you refresh or deselect and select the token again.

[Picture example](https://www.dropbox.com/s/5ndu16r8mcu1sik/2021-07-08%2011-18-45.gif?dl=0)

**Comment by Drental** [comment]
that is currently true of all updates in all systems, the reload seems to be borked.

*investigating*

**Comment by Drental** [comment]
Fixed in 1.14
