### ISSUE TITLE
[OSE] Old-School Essentials support

### ISSUE THREAD

**Issue by anthonyronda** [Drental/fvtt-tokenactionhud#231]
I'm the maintainer of [`ose`](https://github.com/vttred/ose) and I'm planning to contribute a PR for OSE support this weekend.

I've never used Token Action HUD, so I'll point OSE fans here to ask them which actions they'd like support for

**Comment by Drental** [comment]
at the current time I have no intention to add support for additional systems. Closing to get a better overview of the state of the module.

If you still make a PR I'll get it in, no worries.
