### ISSUE TITLE
Module Compatibility

### ISSUE THREAD

**Issue by ShadowRedfox** [Drental/fvtt-tokenactionhud#240]
There is issue with compatibility with module Custom Abilities & Skills: https://foundryvtt.com/packages/dnd5e-custom-skills

I've tried to make Issue there, and I got a reply with what's wrong. And to make modules compatible with each other, this one needs a fix.
https://github.com/misthero/dnd5e-custom-skills/issues/6

I hope this is something that can be fixed, as I'd like to use both modules in my games.

**Comment by Larkinabout** [comment]
It looks like custom abilities and skills are now appearing in the HUD when added by this module. I'll leave this issue open for potential support for hiding core abilities and skills that are hidden by the module.

**Comment by Larkinabout** [comment]
Abilities and Skills can now be removed from the HUD as desired in the new [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e).
