### ISSUE TITLE
Forbidden Lands - Sleigth of Hand & Animal Handling not working

### ISSUE THREAD

**Issue by pfeiffermit3f** [Drental/fvtt-tokenactionhud#241]
Hi,
just tried out the Token Action HUD for Forbidden Lands. It seems Sleigth of Hand & Animal Handling do not pull the character's stats referring to these skills when activating through the HUD. Can you give it check at some point?
Cheers

**Comment by Larkinabout** [comment]
Fixed in release 3.0.4.
