### ISSUE TITLE
Forbidden Lands-Only English Language Preference in Core Setting is working

### ISSUE THREAD

**Issue by Cougy-6185** [Drental/fvtt-tokenactionhud#242]
Hello,
If I switch the Language, in **Game Settings -> Core Settings -> Language Preference,** to anything other than English, Token Hud won't work correctly.
The different popup appears but when I click on Attributes, Attack etc ... the popup window doesn't take the Stats Sheet into account at all. All the Talents, Attacks etc... doesn't show anyting.
You can simply test this by changing the Language Preference in Core Settings, even with the base game system.

**Comment by Dolgrenn** [comment]
I confirm the issue. In the system there is a mapping table (In the console if you type CONFIG.fbl.skillAttributeMap you can see it) where everything is in English, so it only works for Endurance in French because it is the same spelling in both languages.

**Comment by Larkinabout** [comment]
Tested as working in release 3.0.3 (v10).
