### ISSUE TITLE
Forbidden Lands - Monster attacks not rolling

### ISSUE THREAD

**Issue by pbrasi** [Drental/fvtt-tokenactionhud#243]
Hi,
thanks for the great module, I love it.
Only issue I had is that the attacks for monsters, although they appear correctly with the right icons in the HUD, do not pop up any roll window.
Also, I confirm that Sleight of Hand and Animal Handling skills always report 0 as dice pool

Cheers,
MP

**Comment by Dolgrenn** [comment]
Monster attacks work with a random table that rolls a die and defines which attack will be used. We should be able to use this random table with one click instead of seeing the different attacks in token action hud.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.4.
