### ISSUE TITLE
TAH not working for NPCs

### ISSUE THREAD

**Issue by Mrfikser** [Drental/fvtt-tokenactionhud#246]
This is for PF2. TAH opens for my PCs when I click them but no longer seems to open when I click on my NPCs. I don't -think- I've made any changes other than updating to version 2.2.29 recently.

**Comment by Zadantur** [comment]
Same issue.
If I select a PC, then I see their HUD, but if I select and NPC it sticks as the last PC selected.
If I select an NPC first, there is no HUD displayed. 
Running Foundry Version9 - Build 269, Pathfinder 2E 3.13.5.16, TAH 2.2.29

**Comment by badrath** [comment]
Same issue, discovered it a couple of days ago (2022/08/24) but did not confirm it until today.
Checked if it was a conflict with other modules, however, the issue persists when TAH is the only module activated.

Foundry Version: 9
Build: 269
Pathfinder 2E: 3.13.5.16
TAH: 2.2.29

**Comment by Drental** [comment]
Fixed. Apologies

**Comment by Mrfikser** [comment]
Thanks for the fast turn around!!!

**Comment by badrath** [comment]
Thanks for the rapid fix and the fantastic module!
