### ISSUE TITLE
Module has 30 dependencies - mostly, if not completely, systems

### ISSUE THREAD

**Issue by strongpauly** [Drental/fvtt-tokenactionhud#254]
Surely I don't need all these systems to use this module:

<img width="611" alt="Screenshot 2022-09-03 at 12 13 22" src="https://user-images.githubusercontent.com/853954/188267900-e4d37b33-498c-4aa0-a139-9a94eb8d7076.png">

**Comment by Drental** [comment]
oh, looks like they changed that bit a bit more than I thought, I was just trying to declare compatibility.

**Comment by Drental** [comment]
okay, I did declare things as best I could, for now you can just close the message and ignore.

**Comment by strongpauly** [comment]
Is this a bug in core foundry then?

**Comment by Drental** [comment]
yes.

**Comment by strongpauly** [comment]
Found it: https://github.com/foundryvtt/foundryvtt/issues/8066

**Comment by Larkinabout** [comment]
Fixed in Foundry VTT v10.285.
