### ISSUE TITLE
HUD is messed up with multiple very large spellcasting entries

### ISSUE THREAD

**Issue by NikolasTzimoulis** [Drental/fvtt-tokenactionhud#264]
![unknown](https://user-images.githubusercontent.com/380852/189911435-52b965d8-59d9-420b-8eac-644d32d2efa5.png)

See pic above for details. From what I can tell the following problems occur: 

- Entries intersect.
- Icons missing
- Wrong order of spellcasting entries compared to character sheet

**Comment by Larkinabout** [comment]
Do you have the Dorako UI enabled in the settings? Of so, try switching back to the default UI or hop back to 3.0.4 until this is fixed.

**Comment by NikolasTzimoulis** [comment]
Thanks, that's a nice workaround!

**Comment by Larkinabout** [comment]
Fixed in release 3.0.6.
