### ISSUE TITLE
SWADE: Add Main Hand/Off-hand/Two Hands/Equipped icons to Gear buttons

### ISSUE THREAD

**Issue by Larkinabout** [Drental/fvtt-tokenactionhud#268]
Add the Main Hand/Off-hand/Two Hands/Equipped icons from the default character sheet to the Gear buttons on the HUD to indicate how a gear is held.
![SWADE Equip Icon](https://user-images.githubusercontent.com/105953297/190028392-222c0f43-0cf7-49b0-a7ff-42e80242d516.png)

**Comment by mclemente** [comment]
Would something like this be ok?
![image](https://user-images.githubusercontent.com/5288872/234716930-63bbf797-03a3-46e3-a76b-a244ddd0b526.png)

**Comment by CyrilRonseaux** [comment]
As a SWADE GM and player, I would be perfectly ok with the display you propose. Totally does the job.
