### ISSUE TITLE
SWADE: No Tab for gear

### ISSUE THREAD

**Issue by grendel111111** [Drental/fvtt-tokenactionhud#269]
With the update to 10 the gear tab seems to be missing for SWADE (or I'm not seeing it)
![image](https://user-images.githubusercontent.com/80164119/190287577-037f3b0f-bd21-4a8b-90c0-d7ea944bb665.png)

**Comment by Larkinabout** [comment]
Do you have the items equipped or in your hand?

**Comment by grendel111111** [comment]
I'll check. That might be something new.

**Comment by grendel111111** [comment]
Thank you. It needs to be equiped now.
