### ISSUE TITLE
[Feature Req] dnd5e - Improvements to Inventory handling (inspiration from PF2)

### ISSUE THREAD

**Issue by apoapostolov** [Drental/fvtt-tokenactionhud#271]
Create a new section Weapons and put it before Inventory. All weapon type items should appear in Weapons section and not in Inventory section. This recreates something similar to PF2 Strikes section for 5E. This helps keep weapon attacks separate from huge inventory lists

**Comment by Larkinabout** [comment]
I'm thinking of a big rework to allow users to choose where they want subcategories to go, but it'd take a while to achieve. For now, I'll see about adding this as a setting option alongside grouping skills and abilities (#117).

**Comment by Larkinabout** [comment]
This will be available once Pathfinder 2 is supported by [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core).  See Larkinabout/fvtt-token-action-hud-core#11.
