### ISSUE TITLE
[The Forge] UI Bug

### ISSUE THREAD

**Issue by AetherianRPG** [Drental/fvtt-tokenactionhud#272]
There seems to be some sort of issue with the module and The Forge. There's nothing on the console, but the UI doesn't behave as it should:

1. The Dorako UI is always the used one, even if the Foundry VTT style is selected in the module settings.
2. The dropdown menus do not work as intended, making some options impossible to be clicked.

**The same world files** outside The Forge **do not** have this issue.

![HUDBug001](https://user-images.githubusercontent.com/68928934/190445281-d2ec14e3-ba4b-4680-890f-d63844b3f368.gif)

The only module active with Token Action HUD at the time of this report was Color Picker and The Forge module (which is impossible to turn off now).

**EDIT**

Found this on the console and it only appears on The Forge:

![Forge002](https://user-images.githubusercontent.com/68928934/190448216-e37b118f-8e1d-4793-bc28-1c950e2769c7.PNG)

**Comment by Larkinabout** [comment]
Does the issue still exist if you go back to release 3.0.5?

**Comment by AetherianRPG** [comment]
No, it doesn't. And like I said, this issues seems to exist only on The Forge. I even exported the same world and opened it locally with no issues. Thank you!

**Comment by Larkinabout** [comment]
I think I've found the issue: The Forge has the version number in the module's path, so it's not finding the path to the CSS files based on the string I'd used. Will you just be able to confirm for me by letting me know what the path to the token-action-hud.css file is in the HEAD tag please?

**Comment by AetherianRPG** [comment]
I'm terribly sorry, sir. But I don't know anything about coding, how exactly do I access this information for you?

**Comment by Larkinabout** [comment]
It will vary depending on your browser, but generally:

- Press F12 in your browser once Foundry has loaded up.
- Click on the Elements tab.
- Expand the \<head\> tag using the little arrow.
- Take a screenshot.
It should look something like this:
![Developer Tools](https://user-images.githubusercontent.com/105953297/190515826-2564034f-8947-42c1-8da9-1f85aa166d5a.png)

**Comment by AetherianRPG** [comment]
![TokenActionHUD001](https://user-images.githubusercontent.com/68928934/190830652-2df7c575-fe23-490f-bc98-eef6ed596e0a.PNG)

**Comment by Larkinabout** [comment]
Great, thanks. Just as suspected, so there'll be a fix in the next release. I'm just working on some other bits, so expect a release in the next day or so.

**Comment by Drental** [comment]
fixed it just now, together with a second bug (I hope) https://github.com/Drental/fvtt-tokenactionhud/commit/715edde88718c86af13e938e4c12408cef9e431c

![image](https://user-images.githubusercontent.com/74384067/190969744-8099e9b4-93d4-4ca7-8daf-f3b513819c77.png)

anything on your side that would hold up a release Larkinabout?

**Comment by Larkinabout** [comment]
I'd also fixed it in another branch that I'm working on, but I haven't made any changes to master if you want to push a release with just that fix. Most of the other changes in the branch are enhancements, so it can wait.

**Comment by Drental** [comment]
good, I'll release this fix then :)
