### ISSUE TITLE
Make ColorPicker module dependency optional

### ISSUE THREAD

**Issue by stwlam** [Drental/fvtt-tokenactionhud#278]
Can this dependency be made optional? Token HUD has been around since inception without the need for any dependencies, and adding one at this stage for such a small feature may not be welcomed by those wanting to contain module bloat.

**Comment by Larkinabout** [comment]
The module will already work without the Color Picker module installed. The Color Picker module adds an alpha color picker to simplify color selection for some module settings, but it's otherwise optional.

**Comment by stwlam** [comment]
It can't be activated without the dependency.

**Comment by stwlam** [comment]
![image](https://user-images.githubusercontent.com/106829671/191576727-84628514-878d-4bdc-8247-5876e45356c6.png)

**Comment by Larkinabout** [comment]
Ah, for some reason I believed you could choose to still run modules without their dependencies enabled. I'll take a look and see what's possible.

**Comment by Larkinabout** [comment]
Resolved by @mouse0270 in release 3.0.9.
