### ISSUE TITLE
Customisable Categories and Subcategories

### ISSUE THREAD

**Issue by Larkinabout** [Drental/fvtt-tokenactionhud#281]
Use the existing category manager to allow users to customise categories and subcategories.

- Allow any category to be deleted, including default core categories.
- Allow categories to be created/renamed.
- Allow core subcategories to be added to any category, e.g., create a Weapons category, remove the Weapons subcategory from the Inventory category and add it to the new Weapons category.
- Allow categories and subcategories to be reordered.
- Add lock/unlock button to the HUD to allow hidden categories (those without any subcategories) to be displayed in order to manage their content.

**Comment by Larkinabout** [comment]
#28, , #271

**Comment by Larkinabout** [comment]
![tah-development-progress](https://user-images.githubusercontent.com/105953297/192076091-c4e6b5f6-73c5-4675-9c21-87c95b64d17c.gif)

**Comment by Larkinabout** [comment]
![tah-actions-customisation](https://user-images.githubusercontent.com/105953297/192918499-748091e1-b569-4f89-941e-b3dea0cdf41c.gif)

**Comment by Larkinabout** [comment]
![tah-customisation-compendiums](https://user-images.githubusercontent.com/105953297/193467114-574a60f2-21cd-4897-8975-4d585a3c012b.gif)

**Comment by Truncated** [comment]
Would it be possible to allow specific macros to be added as an item to any of the categories / sub-categories?

My thought is that macros seem to fill gaps in many game systems where functionality is either pending or simply impossible for the category of item. Being able to add 1+ macros in any of the hud options would not only make it infinately flexible but also consolidate the user experience. My less tech savvy players have a huge issue keeping track of "where things are", and this would be a huge help to that, alone.

**Comment by apoapostolov** [comment]
You can already do this. Create a compendium, add your macros in it, and
use that compendium in a custom category. I do this for basic action macros
in PF2.

**Comment by Truncated** [comment]
> You can already do this. Create a compendium, add your macros in it, and use that compendium in a custom category. I do this for basic action macros in PF2.

That's an interesting work-around which definately has a place, but not really what I'm talking about. The approach you mention has two logical outcomes I can see:
1. One compendium is made with all the macros in it... so it may be a hodge-podge of purpose, but lowers the number of categories across the top. Regardless, it's an extra category box, and essentially moves the Macro Shortcut Bar to the HUD. That's valuable in some contexts, for sure.
2. You make multiple compendiums to categorize them by purpose (as you do with Basic Actions), which would lead to a bloated number of menu options... and still segregated. Less valuable in the sense of screen real-estate, user experience, and complexity but still has contexts that is beneficial in.

What I'm suggesting is a true integration - One might use a macro as a weapon attack, a spell casting approach, or a utility, or something else entirely. I'm looking to have the macro(s) identified to show up in the menu drop-downs just as Longsword would in Weapons or Bless would in Spells for the different category menus.

This way, the user goes to Spells and all their spell options are in one place, whether from their class / spellbook or the macros that are used for those special cases like Polymorph or Summon Monster, etc.

This way, attacks or spells are all in the same place depending on how you want/need to handle them in your system of choice. Having the macros in separate categories is like having settings in diffierent screens; out of sight, out of mind, and just makes it easier to accidentally forget them.

**Comment by Larkinabout** [comment]
The first iteration of this customisation update is unlikely to have this functionality, but it's a good next step.

You will already be able to add a custom subcategory to any category and then add your macros to that custom subcategory to have your macros alongside your core actions, but currently adding either macros to core subcategories or core actions to custom subcategories is not possible.

**Comment by Larkinabout** [comment]
This feature is included with [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core). The macro feature request made here has been moved to Larkinabout/fvtt-token-action-hud-core#19.
