### ISSUE TITLE
PF2e Thrown Weapons Only showing melee strikes

### ISSUE THREAD

**Issue by elfenari** [Drental/fvtt-tokenactionhud#282]
The 5 buttons for rolling an attack appear in the character sheet for both the melee and ranged versions of a thrown weapon, but only the melee version shows on the Token Action HUD.

**Comment by esheyw** [comment]
I cannot reproduce this with mod/system/foundry current and no other modules. May be related to a pf2e system bug that got fixed since then?

**Comment by Larkinabout** [comment]
I've tested this with Foundry VTT v10.286, Pathfinder 2nd Edition 4.13 and Token Action HUD 3.0.8 and also cannot reproduce this issue. @elfenari, is this still an issue for you?

**Comment by apoapostolov** [comment]
This is no longer an issue with thrown weapons with one exception - the thrown attack is not marked as such, maybe using the same thrown icon used in the character sheet would be possible?

**Comment by apoapostolov** [comment]
I will close this issue and open a new one.
