### ISSUE TITLE
Earthdawn Doesn't show weapons in Combat Tab in V10

### ISSUE THREAD

**Issue by WEKarnesky** [Drental/fvtt-tokenactionhud#283]
After upgrading to v10, the equipped weapons no longer show up in the Combat tab to click.

**Foundry Version:** 10
**Build:** 285
**Earthdawn System:** 0.7.0
**Token Action Hud Version:** 3.0.8

**Comment by Larkinabout** [comment]
Fixed in release 3.0.9.
