### ISSUE TITLE
[Feature Request] Have the HUD be over character sheets

### ISSUE THREAD

**Issue by GhostwheelX** [Drental/fvtt-tokenactionhud#284]
Might it be possible to have the HUD appear on top of character sheets when an option pops up? Often character sheets can hide the options in the dropdown menu.

Thanks!

**Comment by Larkinabout** [comment]
Would you be able to provide a screenshot of what you mean please?

**Comment by GhostwheelX** [comment]
Yep :-)
![image](https://user-images.githubusercontent.com/68725723/192093366-2c571b03-ccce-4704-be15-85441108d9d5.png)

See how the options are completely covered by the character sheet? Might it be possible for them to be "over" it so that you could click on them even when a character sheet is open?

**Comment by Larkinabout** [comment]
Added in release 3.0.10.
