### ISSUE TITLE
[Feature Request] Tooltip Support for Actions inside the HUD

### ISSUE THREAD

**Issue by NuptupTDOW** [Drental/fvtt-tokenactionhud#287]
So, I was having a conversation several months ago with the system devs for the system I play, and it has led me here to make it a formal request. You can see the full discussion over here (https://github.com/EndlesNights/dnd4eBeta/issues/201), but here's a screenshot of the design intentions.

https://user-images.githubusercontent.com/58280840/160193488-7e70b239-6e78-4cc5-a3be-0606fe76b642.png

Pretty much, just whenever you move your mouse over a button inside the TAH, it would generate a "Tooltip" either near the cursor, or at a pre-assigned location chosen by the user (a corner or bottom-center for example) that would show "pretty much" what will appear in chat, minus any actual rolls.

**Comment by Larkinabout** [comment]
Looks good. Only issue I can potentially see is how to avoid the tooltip getting in the way for those actions that will 
inevitably end up underneath it because of how TAH generates its button layout.

I'm working on core changes to how TAH handles customisation of the bar, so this will have to wait until after then (unless someone else picks it up), however it's a worthwhile enhancement idea.

**Comment by NuptupTDOW** [comment]
My main suggestion for that would be a client-side option in the foundry settings that allows a user to assign where it would appear. For example, in most MMO's with tooltips like that, you can set where you want it to be placed so it doesn't block your ui. 

For me personally at least, I have foundry set up so that TAH is near the top-left of my screen (growing downwards) so I would personally set the tooltip position to always appear in the bottom-right corner, right next to my chat log, that way it would almost never interfere with buttons on TAH itself, and only potentially cover up something visible on the map while hovering over a button. 

Also, typing this out gave me a second suggestion/request. Can you please add a flipped layout as an option? Instead of being the bar at the top and buttons dropping down below it, make it so that the bar could be at the bottom with the buttons growing up out of it towards middle of screen? This would allow it to take a "Permanent" place at the bottom of a user's screen, and effectively replace (or sit on top of) the built-in macro bar.

**Comment by Larkinabout** [comment]
> Also, typing this out gave me a second suggestion/request. Can you please add a flipped layout as an option? Instead of being the bar at the top and buttons dropping down below it, make it so that the bar could be at the bottom with the buttons growing up out of it towards middle of screen? This would allow it to take a "Permanent" place at the bottom of a user's screen, and effectively replace (or sit on top of) the built-in macro bar.

There's a sort-of implementation for this already if you untick the Dropdown Categories module setting.

**Comment by NuptupTDOW** [comment]
So, I had no clue that existed, but messing around with it, it's pretty much almost EXACTLY what I was looking for, except with like.., 2-3 tweaks. 

1: (and this one is kind of a nitpick with regular lay-out as well) but I think it would be better if the buttons that dropdown/popup would always "Rule" in-line with the furthest left edge of the TAH interface. So, if you are using it, regardless of dropping down or up, if "Abilities" is your first category, no matter WHICH of them you open, they will dropdown/popup where the furthest left entry is in-line with the "Abilities" category button. This would help keep everything centralized in a predictable area instead of constantly "stair-stepping" to the right with each additional category. 

2: Remove the scroll bar entirely on the pop-up version. It's not present (to my knowledge) on the dropdown version, so it shouldn't be in the popup version either. It's a bit annoying when you are scanning through things and have to pause to scroll up to confirm the thing you're looking for isn't there. 

3: (This would potentially be fixed by # 1, and I've also had this issue with dropdown mode too, but to a lesser extent) but, in the popup mode, it seems to "re-close" much more sensitively than the dropdown method. I can take my cursor, more it over abilities, and then move up and it loses track and closes the category. I think this could be remedied alongside the # 1 I mentioned above by simply making the category "Viewing box" completely envelope the TAH Header bar so that there's no "empty space" to lose the cursor in when it's popped open in either direction. Then just update the logic of the category header buttons so that the category only closes when you mouse over a different category, or when you _**click**_ on something other than TAH, similar to deselecting something on the map. This would be a really intuitive change that most people would very quickly pick up and would fix this sometimes annoying "bug?"/interaction.

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#23.
