### ISSUE TITLE
Equipment and Features not working in Foundry V10 Starfinder 

### ISSUE THREAD

**Issue by SebastianH17** [Drental/fvtt-tokenactionhud#290]
Starfinder works pretty well on V10 but the Token Action Hud struggles to do something, like posting the weapons:

![image](https://user-images.githubusercontent.com/84858570/192900667-bf0ce5de-2e70-4009-afcb-3eb3477a0ab2.png)

![image](https://user-images.githubusercontent.com/84858570/192900732-8460dba4-2d82-4e26-8990-08034a2ed668.png)

Both Equipment and Features do not seem to do anything, but skills and saves work perfectly fine. 

I saw that some Starfinder issues are on the back burner, but I am happy to mention that they releases a V10-compatible version last week ^^ 

---
Your hard work is super appreciated, this module helped me jump on board with Foundry, and I am so darn happy about that ^^

**Comment by Larkinabout** [comment]
Nice styling for the HUD!

Good to hear there is a v10-compatible version now. Will have a look at fixes for the nexrt release.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.10.
