### ISSUE TITLE
HUD not working with enhanced conditions from CUB in FVTT v10

### ISSUE THREAD

**Issue by brother-oak** [Drental/fvtt-tokenactionhud#291]
Note this used to work in FVTT v9

If this module is enabled with the Combat Utility Belt module, and enhanced conditions are switched on in that CUB module, then setting an enhanced condition on a token using the token action HUD results in the condition being set AND unset at the same time - so no overall effect (both the + condition text and the - condition text appear and float up/down, which is why it is obvious that the condition is being set and unset each time it is selected).

Note this ONLY happens with enhanced conditions (if the original conditions are left in the list and selected, they are set and unset correctly in the Token Action HUD, but any new/enhanced conditions still show this problem)

If the condition is set using the original token HUD, it sets correctly (which is why I am assuming this is a problem with the TAH module, not the CUB module)

Tested using 
FVTT v10 build 286
DnD 5e v2.03
CUB v1.10.1
TAH v3.0.9

Tested with no modules other than CUB and TAH running.

**Comment by Larkinabout** [comment]
Looks like support for CUB is included, so likely something has changed with core or CUB that's broken it.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.10.
