### ISSUE TITLE
GURPS Advantages & Conditional Modifiers are not displaying correctly with new version of GGA.

### ISSUE THREAD

**Issue by jcklemme** [Drental/fvtt-tokenactionhud#292]
They display as show in this screencap
![image](https://user-images.githubusercontent.com/21014259/193340911-aa941cdf-e584-4feb-87b1-a2c8e2a5f653.png)

**Comment by crnormand** [comment]
This will be fixed in the next release.   I've found the issue and I am working on the PR.

**Comment by jcklemme** [comment]
Wonderful, thank you very much!

**Comment by Larkinabout** [comment]
> This will be fixed in the next release. I've found the issue and I am working on the PR.

Is this to fix in Token Action HUD or the GURPS system?

**Comment by crnormand** [comment]
TAH... plus it will include enhancements to the GURPS support.

**Comment by crnormand** [comment]
PR is ready:   https://github.com/Drental/fvtt-tokenactionhud/pull/293

**Comment by crnormand** [comment]
The change to TAH is completely backwards compatible.   It just adds support for systems (like GURPS), that might want to send raw HTML names.

**Comment by TheFabulousIronChef** [comment]
Not sure if this is related but seems to be:
https://github.com/crnormand/gurps/issues/1626

**Comment by TheFabulousIronChef** [comment]
Basically: Neither skills nor spells show; disadvantages list the disadvantage name but then a string of random numbers after it. Interestingly, you can click that weird string and it will roll the control roll ... it's just the TAH display that is off.
![image](https://user-images.githubusercontent.com/46587602/193455786-9fcda3e7-5376-4ec5-a9f4-54c818e2828c.png)

**Comment by Larkinabout** [comment]
Resolved by @crnormand in release 3.0.10.
