### ISSUE TITLE
Ability to add full macro compendiums no longer working

### ISSUE THREAD

**Issue by Symon-S** [Drental/fvtt-tokenactionhud#295]
This may be pf2e specific, but macro compendiums are no longer added into TAH.
![image](https://user-images.githubusercontent.com/81383360/193732015-67f5963a-c2a6-4475-a7fa-1bfbfcb9e2a9.png)
![image](https://user-images.githubusercontent.com/81383360/193732051-749ea496-b8bb-48c2-a397-5094a77ac898.png)
![Peek 2022-10-03 22-11](https://user-images.githubusercontent.com/81383360/193732787-539ae1c1-2779-4ca4-8d81-d0b662d909c9.gif)

**Comment by Larkinabout** [comment]
This is specific to pf2e's built-in macros. Custom user macros still function.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.11.
