### ISSUE TITLE
Uncaught ReferenceError: s is not defined

### ISSUE THREAD

**Issue by aedgaruk** [Drental/fvtt-tokenactionhud#298]
Hi,

Since upgrade to FVTT v10 I'm getting this error thrown (see image):

![image](https://user-images.githubusercontent.com/111492074/194108557-b82cd215-383f-424a-8e94-42265586262f.png)

... something around Line: 625

![image](https://user-images.githubusercontent.com/111492074/194110562-21acab91-ebab-4b0e-b7ac-53bf608f893c.png)

Cheers
Andy

**Comment by Larkinabout** [comment]
Fixed in release 3.0.11.

**Comment by aedgaruk** [comment]
Retested and Passed - Thank You
