### ISSUE TITLE
SWFFG Support broken in v10

### ISSUE THREAD

**Issue by JonMazu** [Drental/fvtt-tokenactionhud#299]
With the move to V10, it seems that support for SWFFG has broken. Leading to an Error when clicking on any tokens, and the hud not showing up.
![image](https://user-images.githubusercontent.com/98606342/194586197-018eb414-63dd-4084-96dc-f6ac5794c4eb.png)

This was done in the lastest version of the System, which is currently in Beta. But I vaguely remember having the same issue with the last stable Version of SWFFG

FOR more info. This is being ran in the Genesys mode for the system with a custom skill sheet. Not sure if thats important but I included it just in case.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.11.
