### ISSUE TITLE
Ability to bring up the hud in scenes with no tokens

### ISSUE THREAD

**Issue by Drental** [Drental/fvtt-tokenactionhud#30]
use game.user.character for a default HUD when nothing is selected.

Most likely a lot of work

**Comment by Drental** [comment]
worked already (by defaulting to game.user.character)

**Comment by Drental** [comment]
*needs the token after all, reopening

**Comment by nschoenwald** [comment]
Just want to chime in to say that this would greatly streamline and enhance my foundry experience because I like to use atmospheric scenes without tokens on them, but would still love my players to have the action hud for quick access to rolls.

**Comment by Larkinabout** [comment]
This feature is available in [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core) and developments of this nature will now continue there.
