### ISSUE TITLE
Token action hud is showing a black box around

### ISSUE THREAD

**Issue by danil0man** [Drental/fvtt-tokenactionhud#300]
Hey. This just started yesterday when I updated foundry to 10.287. There is a black box around the different menus. IT was invisible until yesterday. Do you know how I could make it transparent again?
![image](https://user-images.githubusercontent.com/72052103/194671611-0002a1f9-43d1-46e3-b133-abbc99f508e5.png)

**Comment by Larkinabout** [comment]
There's an issue with defaults for the ColorSettings module in Token Action HUD. Looks like the latest version of Foundry caused some settings to reset.

You can either try to set the colors manually using the color pickers in the Token Action HUD module settings or install the Color Picker module, which will override the Color Settings module.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.11.
