### ISSUE TITLE
swade: Power Points

### ISSUE THREAD

**Issue by mafamac** [Drental/fvtt-tokenactionhud#303]
It doesn't show the current power points available. it always shows the maximum. For example, char has 15 total power points and 15 remaining. it shows 15/15, after consuming some points, char has 11 points and the bar still showing 15/15.

**Comment by Larkinabout** [comment]
![swade-power-points](https://user-images.githubusercontent.com/105953297/195956954-192d28aa-6a9d-4e7f-bf13-244131ae3508.gif)

I have tested this on Foundry VTT 10.288, SWADE 2.0.6 and Token Action HUD 3.0.11 and could not replicate the issue. I tested with and without Better Rolls 2. If you're not on the latest versions, perhaps try updating. If it still isn't working, try disabling other modules to see if it's an unexpected interaction between modules.

Let me know if you discover anything.

**Comment by mafamac** [comment]
qq: are you logged as DM or player?

I've tested as DM. Also the gear option is not available when the token is a wild card.

I'm sharing a video I made to show the issue related to the pp and the issue related to the gear (with the browser console)
https://1drv.ms/u/s!AjCOtQ8SxmPPmKxDHauoPZh0TOKOlQ?e=qC2Kux

foundry version is 288
swade version is 2.0.6
Token Action Hud version 3.0.11

**Comment by Larkinabout** [comment]
Sorry, would you be able to post the video somewhere that doesn't require sign in please?

**Comment by Larkinabout** [comment]
Nevermind, opening it on desktop let me watch tthe video without signing in. Is the Power Points issue also only for wildcard tokens too? I'll try testing a wildcard token to see if I get the same results.

**Comment by mafamac** [comment]
I haven't tested it. I´ll test as soon as I connect to my foundry, basically my server running on the oracle cloud isn't accessible :/

**Comment by mafamac** [comment]
Got access. Yes, it's working for extras. Also, I logged as player as isn't working.

**Comment by Larkinabout** [comment]
Ok, we're on the same version and I've tested logged in as a player and with wildcard tokens, but they're all working as expected. What other modules do you have installed?

**Comment by mafamac** [comment]
![Captura de tela 2022-10-16 063838](https://user-images.githubusercontent.com/6748594/196020004-e9c1e55c-3760-4d11-8d13-5849fbad5c0c.png)

I've disabled all other modules not useful to test. Also I´ve enabled the debug function and the wild card doesn't have the gear category?!?!?!?!?!?

![Captura de tela 2022-10-16 070104](https://user-images.githubusercontent.com/6748594/196020749-48069d82-a52e-4662-bf3f-2214184665c3.png)

And the extra has
![Captura de tela 2022-10-16 070251](https://user-images.githubusercontent.com/6748594/196020760-b19fb3f1-ca6e-4739-b95c-025ea668f5b6.png)

**Comment by mafamac** [comment]
Got the error,
I should add the gear to the hand, look a new feature, we have to move the gear to the hand of the char to make it available.

sorry take your time on something isn't a bug.

**Comment by mafamac** [comment]
ops.. i missed the issue related to the power points. it still not working.. i will do some tests when I can connect to my foundry.

**Comment by mafamac** [comment]
The issue with the power points only happens when I use actors imported from compendium (from official deadlands or swade modules)

**Comment by Larkinabout** [comment]
Thanks for the update. If I can get any of those for free, I'll see if I can reproduce tonight. Sounds like the prebuilts might be missing something that Token Action HUD is using.

**Comment by Larkinabout** [comment]
I have still had no luck reproducing this on my end.

Will you please be able to try with the Archtypes actors in the Blood on the Range adventure module? If these work for you, I would guess the issue is with the actor data in those other modules.

![swade-power-points](https://user-images.githubusercontent.com/105953297/197666156-9b9f82b4-543f-447c-b7bc-8589614184cf.gif)
