### ISSUE TITLE
Integration with Better Rolls 2 (BR2)

### ISSUE THREAD

**Issue by aedgaruk** [Drental/fvtt-tokenactionhud#304]
Hi,

When selecting a Weapon from the Gear tab in the HUD it doesn't call on BR2, instead it initiates the Core SWADE chat card for combat.

Note: When SWADE Tools is installed (BR2 deactivated) the HUD will call on its popout window for making a roll, hence my raising this issue, namely can TA-HUD initiate BR2?

Cheers
Andy

**Comment by Larkinabout** [comment]
Just to double-check before I look into this, is it possible to set the roll handler in the module settings to Better Rolls?

**Comment by aedgaruk** [comment]
You Sir, are a genius!!

![image](https://user-images.githubusercontent.com/111492074/195358123-b0af12e4-1d75-4080-9a35-725ca8aa344c.png)
