### ISSUE TITLE
Reload Not Adding to Weapon but Does Take From Ammo

### ISSUE THREAD

**Issue by aedgaruk** [Drental/fvtt-tokenactionhud#305]
Hi,

As the title states, the Ammo is depreciated but the amount is not added to the Weapon ...

![image](https://user-images.githubusercontent.com/111492074/195377529-451048a3-52fb-4ed5-b4df-730f1e789d5f.png)

Cheers
Andy

**Comment by Larkinabout** [comment]
I don't see anything regarding the HUD in that particulae error message. Would you please take a screenshot of the HUD and button in question and I'll see if I can replicate on my end. Also, what versions are you running?

**Comment by aedgaruk** [comment]
<scuffs ground looking sheepish>

I had 2 githubs open ... this is for BR2 not TA-HUD ... I may need to have a little lie down ... that's 2 for 2 I've raised with you under spurious circumstances! Apologies!!

![image](https://user-images.githubusercontent.com/111492074/195409554-5016fdbc-e410-4c20-9e7c-30704f4446af.png)

**Comment by Larkinabout** [comment]
I'll happily accept a mistakenly raised issue over actually having to fix something.
