### ISSUE TITLE
3.0.11, PF2, strange freezes of mouse zoom after clicking on elements (low 1:5 repro)

### ISSUE THREAD

**Issue by apoapostolov** [Drental/fvtt-tokenactionhud#306]
When clicking on any options in 3.0.11, usually 1 of 5 times, the HUD will become sticky and will not allow the mouse to zoom or pan the screen until ESC is pressed to force HUD to close down and the selected token to deselect.

**Comment by Larkinabout** [comment]
I have tested this on Foundry VTT 10.288, Pathfinder 2nd Edition 4.2.6 and Token Action HUD 3.0.11 and could not replicate the issue after around 15 minutes of clicking elements and zooming/panning the screen.

I wonder if there is some other unexpected interaction going on with other modules or perhaps even core elements that I'm not using. If you haven't done so already, would you be able try switching off other modules to see if it still occurs with just Token Action HUD enabled? Also, perhaps try reseting the HUD's module settings to see if it's a particular setting combination that is the culprit.

**Comment by apoapostolov** [comment]
I am also unable to reproduce it now, though I haven't done any changes to mods. If I find anything, I will reopen this issue.
