### ISSUE TITLE
pf2e: Add Thrown Icon to Thrown Attacks

### ISSUE THREAD

**Issue by Larkinabout** [Drental/fvtt-tokenactionhud#307]
This is no longer an issue with thrown weapons with one exception - the thrown attack is not marked as such, maybe using the same thrown icon used in the character sheet would be possible?

_Originally posted by @apoapostolov in https://github.com/Drental/fvtt-tokenactionhud/issues/282#issuecomment-1278224354_

**Comment by apoapostolov** [comment]
Thank you for forking this.

**Comment by Larkinabout** [comment]
Hi @apoapostolov, is this what you had in mind?:
![image](https://user-images.githubusercontent.com/105953297/195961338-224bc42c-ea13-4e13-93ff-1f989c9f7d12.png)

**Comment by apoapostolov** [comment]
Yes, precisely that. Thank you!

**Comment by Larkinabout** [comment]
Added in release 3.0.12.
