### ISSUE TITLE
dnd5e - drop-up menu without "click to open"

### ISSUE THREAD

**Issue by JavelinX** [Drental/fvtt-tokenactionhud#308]
Hi all,

there's an issue concerning the drop-up option: when hovering over the appropriate category the corresponding menu opens but as soon as the mouse cursor leaves the field the menu closes. Only work around is to use the "click to open" option in which case the menu stays open.

From my pov it looks like the gap between category and first action ist too big. If compared to the standard drop-down option, it's way bigger.

![image](https://user-images.githubusercontent.com/90550869/195810145-b732cf2d-a4c4-47cb-9203-6f64c09d3065.png)
![image](https://user-images.githubusercontent.com/90550869/195810298-9e6fa78a-cdd3-4657-bb56-4b7ace138842.png)

Best regards!

**Comment by Larkinabout** [comment]
Fixed in release 3.0.12.

**Comment by JavelinX** [comment]
Wow! Thank you so much not only for the quick solution but also the implementation! Awesome module and fantastic developer!
