### ISSUE TITLE
PF2 needs support for Recovery Checks

### ISSUE THREAD

**Issue by apoapostolov** [Drental/fvtt-tokenactionhud#309]
Recovery Checks are PF2's death saving throws. They are available in the character sheet here:

![image](https://user-images.githubusercontent.com/4083812/196169321-b1d397ed-06f8-41d1-8e69-0a668c4b3f31.png)

Add new subsection **Recovery** to section **Utility**. It contains one action **Recovery Check**. It is linked to the Recovery Check to button in the character sheet. If protection from rolling while not dying is needed, it should become clickable only if one of the two:
- token at 0 hp
- token has the Dying condition.

**Comment by esheyw** [comment]
it does, they just are hidden until the actor is at at least dying 1: ![image](https://i.imgur.com/udqN89S.gif)

**Comment by Larkinabout** [comment]
Is some form of this still required or has @esheyw answered it?
