### ISSUE TITLE
PF2 - "The provided predicate set is malformed"

### ISSUE THREAD

**Issue by git-kor-av** [Drental/fvtt-tokenactionhud#312]
Foundry:  v10.288
PF2: v4.2.6
TAH:  3.0.12

The following error is seen in the console when the token is selected:
![TAH_malformed_RE](https://user-images.githubusercontent.com/32276185/197076852-77f85e9f-f60d-4299-b4ae-14415b21a887.jpg)

To reproduce:

1. Create a character
2. Open the compendium and add and equip a Chain Shirt to the character inventory
3. Drag the character to the map
4. Select the character

This doesn't seem to cause any visible problems (other than the error in the console).

**Comment by Larkinabout** [comment]
I have tested this on Foundry VTT 10.288, Pathfiner 2nd Edition 4.2.6 and Token Action HUD 1.0.12 following the steps to reproduce, but am not receiving an error. I wonder if there is some corruption of data that is causing this error?

**Comment by git-kor-av** [comment]
So I've updated to 4.3.0, the character where I was able to reproduce this it is no longer reproducible.  I also am unable to reproduce it on a new character.

**Comment by Larkinabout** [comment]
Thanks for the update.
