### ISSUE TITLE
TAH renders over navigation context menu

### ISSUE THREAD

**Issue by mkahvi** [Drental/fvtt-tokenactionhud#316]
This makes having the HUD near the top quite a nuisance as I can't click the menu items without moving TAH away first.

![Screenshot 2022-10-23 024228](https://user-images.githubusercontent.com/8120158/197366353-9a044051-106c-42f3-b595-f9e2d679407a.png)

**Comment by Larkinabout** [comment]
That's annoying! I would have hoped the menu items would be brought to the top when they're clicked. Only way around this might be to disable Token Action HUD from bringing itself to the top. I'll see what I can do.

**Comment by mkahvi** [comment]
The same is probably true for macro context menu if you have upward direction opening and TAH placed at the bottom.

**Comment by Larkinabout** [comment]
This is the best solution I could come up with to move the HUD out of the way of the context menus. The context menus sit inside the interface element whereas Token Action HUD sits inside an application element, as like other windows, so it's not possible to put the HUD below them.
![token-action-hud-collapse](https://user-images.githubusercontent.com/105953297/197661535-dfd21810-33b2-4090-beb6-25a01a04c480.gif)

**Comment by mkahvi** [comment]
You could maybe add CSS that targets TAH to sets its `z-index` below normal `--z-index-app`'s value . Though I don't know what else that would cause.

**Comment by Larkinabout** [comment]
Solved it!
![token-action-hud-scene-context-menu](https://user-images.githubusercontent.com/105953297/198152643-d82f20da-5c50-44d3-a721-7a2696f6e0d3.gif)

**Comment by Larkinabout** [comment]
Fixed in release 3.0.13.
