### ISSUE TITLE
Legendary and Lair Actions are not localized when using "Group by Action Type"

### ISSUE THREAD

**Issue by benbarbour** [Drental/fvtt-tokenactionhud#318]
![image](https://user-images.githubusercontent.com/487715/198095216-c7adf9a4-a6d5-40ed-959f-c6990c432f67.png)

I think [this key](https://github.com/Drental/fvtt-tokenactionhud/blob/d453494ef748dbadb43ce801074163d002660317/scripts/actions/dnd5e/dnd5e-actions-by-type.js#L17) needs to be `dnd5e.legendaryActions` now. A similar change is needed for `lairActions`, and it looks like `crewActions` may be broken as well, but the key for that was moved to `sfrpg` in the localization file.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.13.
