### ISSUE TITLE
HUD displays vertically for DM only, can't click on hidden buttons

### ISSUE THREAD

**Issue by YourDNDPleasesMe** [Drental/fvtt-tokenactionhud#319]
Hey there!

I'm running Token Action HUD 3.0.13, FVTT V10.288, 5E System 2.0.3.

I tried running FVTT with only Token Action HUD, and the issue remains: The DM's HUD is vertical, and can't be clicked on properly.
Seems also all things that can be clicked on bring up a new window, erroneously. 
See video!

https://user-images.githubusercontent.com/87000878/198815360-f2f3c715-5167-4f4d-ba38-ebf5245c9001.mp4

**Comment by Larkinabout** [comment]
Try deleting the module and reinstalling. It looks like an issue with the CSS. What browser is the DM using?

**Comment by YourDNDPleasesMe** [comment]
I will try removing it and reinstalling. I am the DM and I was using Chrome. 

I saw one other person on FVTT discord with the same issue, they seem to have fixed it with a server restart. 

https://discord.com/channels/170995199584108546/722566083499786352/1035786016147111986

**Comment by YourDNDPleasesMe** [comment]
I can confirm that rebooting my server fixed the issue. Thanks!

**Comment by Larkinabout** [comment]
Thanks for the update.
