### ISSUE TITLE
PF1 Spellbook names are incorrect

### ISSUE THREAD

**Issue by mkahvi** [Drental/fvtt-tokenactionhud#320]
I guess it's reading the `.class` value from the spellbook:  
![Screenshot 2022-10-31 052929](https://user-images.githubusercontent.com/8120158/198925362-628d3e7c-c396-4cb8-a580-6f45f229b9b5.png)

The system should provides good spellbook name in `.label`, for example `system.attributes.spells.spellbooks.primary.label`

`.label` was not previously available, so it's understandable it was not used when this was originally implemented.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.14.
