### ISSUE TITLE
[SWADE] Entangled behave erroneously

### ISSUE THREAD

**Issue by sanpats** [Drental/fvtt-tokenactionhud#322]
In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

> Please share the following basic details about your setup.

- Foundry VTT Version: 10.288
- Operating System: Windows 11
- How Are You Using Foundry: Chrome via The Forge VTT
- Modules Enabled?: [yes] Token Action HUD

### Issue Description

> Please provide a description of your issue below. Including console error messages, screenshots or videos can be particularly helpful.

When using SWADE System set to use Fantasy Companion Entangle (Entangled causing Vulnerable instead pf Distracted):
![image](https://user-images.githubusercontent.com/22677493/197847651-2b7868b3-1e3f-408d-b364-2fd90dd22486.png)

Setting Entangled via Actor Sheet behave correctly:
![image](https://user-images.githubusercontent.com/22677493/197847965-b3f2ee4c-e448-42f6-95cc-627fb4b73ebd.png)
![image](https://user-images.githubusercontent.com/22677493/197848093-10d54072-0a11-4b91-b25a-035e0911089f.png)

But setting Entangled via Token Action HUD behave erroneously:

![image](https://user-images.githubusercontent.com/22677493/197848314-a8017b55-6d6b-4baa-a815-cb41463acbaa.png)
![image](https://user-images.githubusercontent.com/22677493/197848370-a8b2678a-35e3-40f5-8086-3c817b4acb54.png)
![image](https://user-images.githubusercontent.com/22677493/197848403-ef68db3c-ae35-491f-95ee-58f9597805b3.png)

### Relevant logs and/or screenshots

> If you have them, please provide relevant logs or screenshots

### Possible Solution and/or Root Cause

> If you have any possible leads to the Root Cause or suggestions for fixes then please provide them here

Normally I use SWADE Tools, but I disabled it already to test and it still behave incorrectly. Token Action HUD set to Core SWADE as roll handler:
![image](https://user-images.githubusercontent.com/22677493/199588058-31c21245-954f-4ea0-af60-d6a706fd954b.png)

**Comment by sanpats** [comment]
I've reported this issue to SWADE System git. This is the reply from the main dev there:
![image](https://user-images.githubusercontent.com/22677493/199588317-9966a461-f0c3-449e-a4e4-a1121519f7a2.png)

**Comment by Larkinabout** [comment]
Hi @sanpats, what's the difference in those images between enabling Entangled on the actor sheet versus the HUD?

**Comment by sanpats** [comment]
@Larkinabout When using SWADE System and set to use Fantasy Companion Entangle option, Entangled status should causing Vulnerable instead of Distracted). The different is actor sheet give Vulnerable, but the HUD still give Distracted like default (Fantasy Companion Entangle option off)

**Comment by Larkinabout** [comment]
Fixed in release 3.0.14.
