### ISSUE TITLE
No "Enable Dragging" Option of 5e

### ISSUE THREAD

**Issue by LoftheT** [Drental/fvtt-tokenactionhud#324]
Just updated to 3.0.13 and the HUD has changed to vertical by default, often leaving options off the top of the screen and I can't drag the HUD either. I went to check in settings and there's no option to enable dragging. Reverting back to 3.0.12 fixes these issues

**Comment by LoftheT** [comment]
Thanks, I'd been in to the server a few times, (and reinstalled the update a few times) but it was only ever on hold - force stopping the server and restarting it has fixed it to be horizontal again, but I still can't move it around and there's no "Enable Dragging" option in the settings

**Comment by Larkinabout** [comment]
Hi @LoftheT, this is what I see on Foundry VTT v10.288, DnD5e 2.0.3 and Token Action HUD 3.0.13. The 'Enabled Dragging' setting it the fifth setting under Token Action HUD:

![image](https://user-images.githubusercontent.com/105953297/200949066-b2d0cf72-ab6b-48ad-986f-ce51730f6caf.png)

It may be worthwhile uninstalling Token Action HUD and reinstalling on the latest version.
