### ISSUE TITLE
PF2e needs support for unidentified effects

### ISSUE THREAD

**Issue by shemetz** [Drental/fvtt-tokenactionhud#325]
The latest release of the PF2E system (v4.3.4) added [the ability to mark effects as Unidentified, which hides them from player view](https://github.com/foundryvtt/pf2e/pull/4608).

However, the module still shows such effects, like this:

![image](https://user-images.githubusercontent.com/6516621/200177704-cc149acf-3916-4a43-bcd1-0957d8c6fec0.png)

The PF2E integration code of this module should change to take this into account and hide them from players (but not from GMs).

**Comment by Larkinabout** [comment]
Not-so-secret-anymore werewolf curse!

**Comment by Drental** [comment]
can pull out the whole section, the system has implemented the last function that I kept that section around for.
