### ISSUE TITLE
Console error: Uncaught TypeError: Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by yjeroen** [Drental/fvtt-tokenactionhud#326]
![image](https://user-images.githubusercontent.com/1303988/200278444-2b24185a-f203-4aa2-a68d-0c7979904b70.png)

If you need any other info let me know.

**Comment by Larkinabout** [comment]
Hi @yjeroen, do you know when this error occurs? Is there something you click on or some other interaction? Also, what versions of Foundry, system and module are you using?

**Comment by yjeroen** [comment]
Can't reproduce.
