### ISSUE TITLE
Is there a way to turn off the scrolling?

### ISSUE THREAD

**Issue by nirurin** [Drental/fvtt-tokenactionhud#327]
Previously I was used to seeing all the spells etc when I hover over the option. Now it only seems to show the first couple levels, and the player needs to scroll to see the rest. 
Which is sometimes fine, but sometimes a bit annoying, so it would be nice to have the option to toggle this behaviour or something... can't seem to find any options for it though?

**Comment by Larkinabout** [comment]
There's no option to turn off scrolling, however the default behaviour is to extend down as much as possible and only start scrolling when there is overflow.

**Comment by nirurin** [comment]
![Screenshot 2022-11-08 024327](https://user-images.githubusercontent.com/3751273/200462402-2bd1617c-bc97-4c32-8628-aa9e8afdcc3e.png)

It seems to only be extending about 2 rows. There's masses of empty space beneath that. It's barely 10% down the screen.

**Comment by Larkinabout** [comment]
Hi @nirurin, this is what I'm seeing on Foundry VTT v10.288, DnD5e 2.0.3 and Token Action HUD 3.0.13:
![image](https://user-images.githubusercontent.com/105953297/200947248-6babea81-3f17-4a26-8156-e0485eab8ce3.png)

It may be a browser-specific issue or perhaps a conflict with another module.

What browser are you using? Will you please also test with other modules disabled and if, if you know how to, please open the browser's console and check to see if you have any red errors.

**Comment by nirurin** [comment]
The issue seems to be a conflict with the 'sidebar macros' module, though I'm not sure how they're related as that module doesn't do anything on the screen... just the sidebar.

**Comment by arcanistzed** [comment]
I posted this reply on the issue on my repository:
> I'm not doing anything other than removing the element and it would be Token HUD's responsibility to adjust its height to fit its contents regardless of whether the hotbar is present.

If you have any questions or comments, I'm open to hearing them, but I don't think this makes sense to resolve on my side because this issue most likely will affect any module that adjusts the elements in the central (#ui-middle) section of the interface.

**Comment by arcanistzed** [comment]
I posted this reply on the issue on my repository:
> I'm not doing anything other than removing the element and it would be Token HUD's responsibility to adjust its height to fit its contents regardless of whether the hotbar is present.

If you have any questions or comments, I'm open to hearing them, but I don't think this makes sense to resolve on my side because this issue most likely will affect any module that adjusts the elements in the central (#ui-middle) section of the interface.

**Comment by nirurin** [comment]
> I posted this reply on the issue on my repository:
> 
> > I'm not doing anything other than removing the element and it would be Token HUD's responsibility to adjust its height to fit its contents regardless of whether the hotbar is present.
> 
> If you have any questions or comments, I'm open to hearing them, but I don't think this makes sense to resolve on my side because this issue most likely will arrive due to interactions with any module that adjusts the elements in the central (#ui-middle) section of the interface.

Makes sense to me, but I wanted to cover my bases by making sure both module devs knew of the issue! Hopefully it can get fixed

**Comment by Larkinabout** [comment]
Token Action HUD

**Comment by Larkinabout** [comment]
Token Action HUD uses the expected elements around it to size itself without overlapping those elements. I'll add in a default to use if an element isn't found.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.18.
