### ISSUE TITLE
[SWADE] Token Action HUD is using obsolete Power Points pool.

### ISSUE THREAD

**Issue by sanpats** [Drental/fvtt-tokenactionhud#328]
As of SWADE System 2.1.2+, there are breaking changes to the structure of power point pool. Currently Token Action HUD is no longer use the power points in the Actor Sheet.

In Actor Sheet, it's 5/10:
![image](https://user-images.githubusercontent.com/22677493/201008083-38ca7f8c-d721-4b4b-bf3c-9d7fbc2b17ae.png)

Token Action HUD is still think it's 3/10:
![image](https://user-images.githubusercontent.com/22677493/201008661-aa00361c-d843-4872-acbe-f4d659a7fcd2.png)

**Comment by Larkinabout** [comment]
Fixed in release 3.0.14.
