### ISSUE TITLE
[PF2] Inventory Functionality to wear items

### ISSUE THREAD

**Issue by apoapostolov** [Drental/fvtt-tokenactionhud#329]
Currently left clicking on the inventory item is posted to chat, and the right-click opens the dialog. This is very useful but when an item needs to be equipped or unequipped, there's no functionality for that. This is very needed for items that have rules/effects in them. The player must go to inventory and switch the item as equipped to get the automation effect, and cannot do it via TAH. 

Here's a proposal - middle-click on an inventory item with the functionality to be equipped is equipped/unequipped depending on its current state. In PF2 items are equipped in 1 Hand or 2 Hands, but there's no strict hands limit, so it is enough if 1 Hand is the default method of equipping an item.

**Comment by apoapostolov** [comment]
Just to let you know, ClipperBlood developed a mod called PF2 Send to Hand which adds an API to open a dialog to manage the state of an item in the inventory. The mod also adds middle-button clicking on Inventory items in TAH, basically this request.

This issue can be closed now.

**Comment by Larkinabout** [comment]
Thanks for the update.
