### ISSUE TITLE
SFRPG - Upgrade to 0.8 API

### ISSUE THREAD

**Issue by trioderegion** [Drental/fvtt-tokenactionhud#33]
Most of the SFRPG extension is operational, but has not been upgraded to the 0.8 API fully.

`The Document#_id property is deprecated in favor of Document#id or Document#data#_id. Support will be removed in 0.9.0`
and
`You are referencing Actor#getOwnedItem(itemId) which is deprecated in favor of Actor#items#get(itemId). Support will be removed in 0.9.0`

As examples.

**Comment by Larkinabout** [comment]
Closing as this module is now supporting Foundry VTT v10.
