### ISSUE TITLE
Other issues with SWADE Power Points (not covered by #303)

### ISSUE THREAD

**Issue by sroakjp** [Drental/fvtt-tokenactionhud#330]
In SWADE characters may have multiple pools of power points. The power point tracker in the HUD only tracks "General" points. Other tools (such as BR2) require that each power be assigned to the appropriate Arcane Backround. But this precludes the tracker in the HUD from tracking or allowing you to adjust the power points.

This may be too much of an ask, but ideally the HUD would have separate tracker and adjustment buttons for each pool of PP.

**Comment by Larkinabout** [comment]
How are these additional Power Point pools added to an actor?

**Comment by sroakjp** [comment]
In the power there is a field called Arcane.
![image](https://user-images.githubusercontent.com/62338951/202608177-b68c0512-0117-45a3-86fa-cb387927d0d4.png)
You put the source of the power there. The sheet will group all powers with same Arcane together and give them a single pool of power points.

![image](https://user-images.githubusercontent.com/62338951/202608243-96d883e2-c8b9-4aa0-aacf-7331d910bccb.png)

If you give a power a separate Arcane it will place it in a separate group and give it its own pool of power points.
![image](https://user-images.githubusercontent.com/62338951/202608491-6ba62bfa-87ac-447a-a614-10119a63c8c6.png)

**Comment by Larkinabout** [comment]
Added in release 3.0.16.
