### ISSUE TITLE
Tormenta20 Support

### ISSUE THREAD

**Issue by TheLohan** [Drental/fvtt-tokenactionhud#333]
Hello, i am a brazilian player of Tormenta20. Recently the game had a bunch of big updates and some features of action hud stopped to work. Actually only some atributes rolls are going right, but what we call pericias and the itens arent going to chat.
![imagem_2022-11-15_201553514](https://user-images.githubusercontent.com/51961163/202044896-b002f59e-cbaa-4e54-9b0c-5b84a68b99d9.png)

**Comment by Larkinabout** [comment]
Fixed in release 3.0.15.
