### ISSUE TITLE
SWADE Running Die Issues

### ISSUE THREAD

**Issue by Neurochimp** [Drental/fvtt-tokenactionhud#335]
Hello,

Thank you for adding this. My group was always going back to the character sheet to click it.

Seems to have two problems though.

It doesn't bring up a prompt to roll the die and second it seems to be using default run die, not the run die with effects tied in. I turned off all modules and still it does not provide a prompt to roll the die. 

The pic I've attached is of a dwarf in my group - his ancestry reduces the running die from d6 to d4. Across the board all my PC's are showing the run die prior to the effect from the ancestry reducing it. 

![Runrun](https://user-images.githubusercontent.com/116909768/202720427-b43157cc-e62a-4105-a832-251d28cff581.png)

Thank you again for getting this in. It'll be a great help once it functions like it should.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.16.
