### ISSUE TITLE
Manifest URL

### ISSUE THREAD

**Issue by crnormand** [Drental/fvtt-tokenactionhud#337]
The V3.0.15 release changed the manifest URL to point to a specific version of the module.json file.   As I understand it (and I could easily be wrong), but I thought it is better to point to a generic module.json file, so Foundry can determine if the module needs to be updated.

![image](https://user-images.githubusercontent.com/8931036/202821389-d45a042d-7826-4c47-b6fa-490cd83dae52.png)

I know that is how we do it with the GURPS Game Aid... but again, I could be wrong.

**Comment by Larkinabout** [comment]
I hadn't thought I'd done anything different this time around, but pointing to the latest would be better. I'll make the change next time around.

**Comment by Larkinabout** [comment]
Closing as the latest release (3.0.15) wasn't ticked at the latest release in GitHub. Will make sure this is ticked for future releases too.
