### ISSUE TITLE
[Feature request] Cyberpunk RED support

### ISSUE THREAD

**Issue by Dom-Odyssey** [Drental/fvtt-tokenactionhud#342]
Would it be possible to add cyberpunk RED support.

Here is a link to their project page: https://gitlab.com/JasonAlanTerry/fvtt-cyberpunk-red-core
They have a wiki set up with to help module developers develop for the system as well.

I enjoy using your module for DnD5e and when running cyberpunk red I realized how much more I miss it when I do not having it.

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#26.
