### ISSUE TITLE
[Feature Request] Request for Twodsix - Cepheus & Traveller (Unofficial) system

### ISSUE THREAD

**Issue by mcstutz** [Drental/fvtt-tokenactionhud#345]
In my D&D group we use your package and it works great!  I just bought some Mongoose Traveller 2E books and want to run a campaign in the Cepheus Module.  I'm new to Foundry and just learning the app, but it would be nice to able to select skills at the top of the screen instead of popping out the char sheet.  Thanks for any help!

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#27.
