### ISSUE TITLE
Can not hide Magic Item category

### ISSUE THREAD

**Issue by dyenrac** [Drental/fvtt-tokenactionhud#346]
Can not hide Magic Item category, Items are already shown in the items category so i would like to hide the magic item category.

**Comment by Larkinabout** [comment]
Hi @dyenrac, what system is this for?

**Comment by dyenrac** [comment]
Sorry for the late reply, I've been down sick.

I'm running a D&D 5e campaign in Foundry version 10.


________________________________

**Comment by dyenrac** [comment]
Magic items are already shown in the inventory section so the magic item section is somewhat redundant. It would be nice if we could hide this section.

**Comment by Larkinabout** [comment]
I'm going to leave this one for the original Token Action HUD as the issue has resolved itself in the new [Token Action HUD D&D 5e module](https://foundryvtt.com/packages/token-action-hud-dnd5e) due to its higher level of customisability.
