### ISSUE TITLE
PF2E: Combination Weapon melee strike chat card damage button uses ranged damage

### ISSUE THREAD

**Issue by eboyle1017** [Drental/fvtt-tokenactionhud#347]
When using the HUD to make a melee strike with a combination weapon, clicking damage or critical in the chat card will use the ranged damage calculation instead. First damage roll is using the damage button in chat, the second damage roll is using the melee damage button in the character sheet.

![image](https://user-images.githubusercontent.com/24398689/204199782-e94bd345-f7d3-4f5e-b6b0-37f44205e0e9.png)
![image](https://user-images.githubusercontent.com/24398689/204199791-bef094cf-acc9-488a-999c-de6a1c053eb8.png)

**Comment by eboyle1017** [comment]
After playing around with this some more, the same thing happens with the damage calculation for thrown weapons such as daggers. When performing the thrown strike using Token Action Hud, and then clicking damage or critical damage in the chat card, it uses the melee strike damage instead of thrown damage (which applies dexterity bonus instead of strength for throwing a dagger).

Noticed this when my rogue was trying to throw a dagger and was getting 1d4+4 damage on a throw, when they have 0 strength and 4 dexterity.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.17.
