### ISSUE TITLE
Create Actions off of a section of the character sheet

### ISSUE THREAD

**Issue by moulson1313** [Drental/fvtt-tokenactionhud#349]
I would like to make a selection based off actions on the character sheet. I have placed arrows on the image of the areas Im trying to reference. (Im using the PF2 system.) 
Thank you. 
<img width="750" alt="Screenshot 2022-12-01 at 4 36 03 PM" src="https://user-images.githubusercontent.com/90971459/205164175-93b63247-c9f9-47d6-beab-e7b7e5562f84.png">

**Comment by Larkinabout** [comment]
Hi @moulson1313, these actions are available to add in the dedicated [Token Action HUD Pathfinder 2](https://foundryvtt.com/packages/token-action-hud-pf2e) module.
