### ISSUE TITLE
[Feature Request] - OLD SCHOOL ESSENTIALS SUPPORT

### ISSUE THREAD

**Issue by prfeitosa** [Drental/fvtt-tokenactionhud#351]
Would it be possible to add Old School Essentials support.

Here is a link to their project page: https://github.com/vttred/ose
They have a wiki set up with to help module developers develop for the system as well.

I enjoy using your module for DnD5e and when running Old School Essentials realized how much more I miss it when I do not having it.

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#28.

**Comment by mrcomac** [comment]
https://foundryvtt.com/packages/token-action-hud-ose
