### ISSUE TITLE
Advantage and Disadvantage shortcuts not working with hud.

### ISSUE THREAD

**Issue by SirAron111** [Drental/fvtt-tokenactionhud#352]
So normally when i press Shift while clicking a skill or save etc it rolls it with advantage and when i do control it does it with disadvantage. on all sheets and all other module additions. Just the hud isn't doing it anymore. It did some time back but for some reason it doesn't check for the pressed keys anymore when clicking on a skill, check or save or when making attacks etc.

Not sure if its a feature provided from midi qol but i am sure it was working well together back in v9. was there any changes?

**Comment by Nalbadin** [comment]
Same problema here.... If you fix this, i'll really appreciate that...

**Comment by Larkinabout** [comment]
Is this for D&D 5e and are you using any roll modules like Ready Set Roll?

**Comment by SirAron111** [comment]
Its for 5e yes and the only module doing anything to rolls is midi qol but i am sure it worked in the past just fine.

**Comment by Larkinabout** [comment]
In Midi QOL's case, Token Action HUD just passes the event forward for it to use. I'll have a look tomorrow evening.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.17.
