### ISSUE TITLE
SWADE Powers

### ISSUE THREAD

**Issue by grendel111111** [Drental/fvtt-tokenactionhud#353]
In SWADE there is a menu for powers, This also allows you to add or remove power points. But if you use all your power points that whole section of teh menu disappears so you can't even add Power Points from the HUD to get it back.
![image](https://user-images.githubusercontent.com/80164119/206859163-f4b43df1-0046-49db-b3bf-de2417d7bb9c.png)
This is with Power Points, when the Power Points run out:
![image](https://user-images.githubusercontent.com/80164119/206859226-520e7441-6a17-4176-8533-5c47e86aa59a.png)
I think the section should stay there so you can add PP through the HUD.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.18.
