### ISSUE TITLE
Show all non-prepared spells enhancement request

### ISSUE THREAD

**Issue by dyenrac** [Drental/fvtt-tokenactionhud#357]
Whenever I update player characters from D&D Beyond the settings for cantrip prepared setting is reset to the unprepared state. It would be nice if there was an option to select cantrip, pact, and at-will  spells separate from  the non-prepared spells,

Love this mod, one  of the best ever.

**Comment by Larkinabout** [comment]
This issue is resolved in [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e).
