### ISSUE TITLE
Item Macro Hook inoperable

### ISSUE THREAD

**Issue by TyphosTheD** [Drental/fvtt-tokenactionhud#36]
I have found with the recent module, edition, and VTT upgrade that item macro hooks no longer seem to function. I've tested that the macro itself still functions from the character sheet.

Could we log this as something to fix?

Thanks!

![TAH error with Item Macro](https://user-images.githubusercontent.com/40187548/125372933-33c05c00-e352-11eb-8d1e-275087511968.png)

**Comment by Drental** [comment]
fixed in 1.1.15
