### ISSUE TITLE
TAH minimizes and shows up again on ESC press, requires multiple ESC presses now to deselect

### ISSUE THREAD

**Issue by apoapostolov** [Drental/fvtt-tokenactionhud#360]
Previously pressing ESC caused the deselection of the token. For some reason, pressing ESC causes TAH to hide with smooth animation, but the token remains selected. I must press ESC multiple times or do area selection on the canvas to deselect tokens.

**Comment by Larkinabout** [comment]
It'll be the downside of treating the HUD like an application  window to allow it to get focus over other windows. I'll see if it's possible to bypass the Esc key when the HUD has focus. Failing that, it might end up having to be a setting to provide one or the other.

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#31.
