### ISSUE TITLE
(PF2E) Duplicate Attack Names on NPCS rolls wrong attack

### ISSUE THREAD

**Issue by PimpWilly** [Drental/fvtt-tokenactionhud#361]
Sample NPC: Palzu

Palzu has two strikes, both named "JAX." One is a ranged strike and one is a melee strike.

Using TAH, it shows both entries, but when you click either one both default to the melee strike only. Theres no way to make the ranged attack from TAH.
(If the names are not the same, it works fine)

**Comment by Larkinabout** [comment]
Fixed in release 3.0.18.
