### ISSUE TITLE
[PF1] Action active/passive state is determined poorly

### ISSUE THREAD

**Issue by mkahvi** [Drental/fvtt-tokenactionhud#364]
Specifically talking about these bits of code:  
- <https://github.com/Drental/fvtt-tokenactionhud/blob/master/scripts/actions/pf1/pf1-actions.js#L533>
- <https://github.com/Drental/fvtt-tokenactionhud/blob/master/scripts/actions/pf1/pf1-actions.js#L543-L547>

Better logic would be simple: `item.system.actions?.length > 0`

It's slightly more reliable, but incorrectly ignores passive "actions".

If you want to be super correct, you could do something like this (untested, but should work):
```js
const actions = item.system.actions;
const unchained = game.settings.get("pf1", "unchainedActionEconomy");
const isNotPassive = (action) => !unchained ? action.activation?.type !== "passive" : action.unchainedAction?.activation?.type !== "passive";
const isActive = actions?.length > 0 && actions.some(isNotPassive);
```
Which also respects the optional unchained action economy which can alter available configuration on the items (especially those made from scratch).

Both of these also remove incorrect fetch from item data for the activation, which is left over cruft data by the system.

**Comment by Larkinabout** [comment]
Hi @mkahvi, pop a pull request in for your changes and I'll accept it for the next release.

**Comment by mkahvi** [comment]
Since the support is being moved to system specific integration modules, I'm closing this.
