### ISSUE TITLE
Features not populating content from HUD

### ISSUE THREAD

**Issue by Geektasticdad** [Drental/fvtt-tokenactionhud#365]
Hello, I'm running Foundry VTT Version 10 Build 291 and the Token Action HUD v3.0.17. When I click on any of the Features options, it adds the title but no content.

![chrome_gH2G9WBx6G](https://user-images.githubusercontent.com/73676044/210107068-e2393da2-56f5-4d96-9b67-6b251747d8b3.png)

However, when I go into the character sheet and click the Feature, I get the content.

![chrome_gpcBJhXUgL](https://user-images.githubusercontent.com/73676044/210107127-ab015dab-842d-4bab-9b77-6221f0426017.png)

I'm also running the following modules:

![chrome_UAT6yPwM3g](https://user-images.githubusercontent.com/73676044/210107215-027ce963-9af8-4993-8206-7c16bf6fc107.png)

![chrome_TMu7hHXddz](https://user-images.githubusercontent.com/73676044/210107220-4220b51d-8db9-4808-9d74-eed906ea53bd.png)

**Comment by Larkinabout** [comment]
Hi @Geektasticdad, I have not been able to reproduce this issue on my end. Top chat card is from Token Action HUD and bottom is from the character sheet:
![image](https://user-images.githubusercontent.com/105953297/211178830-a4257ac6-ede8-4909-98b2-0bfd1b8935eb.png)

There may be an unexpected interaction with another module or perhaps with the content of the description. Will you please try other features to see if the description is included and also try disabling other modules to see if the issue persists.

**Comment by Geektasticdad** [comment]
It appears the issue exists with other features as well. I'll have to go through my Modules and turn them off one at a time. I've got Module Compatibility Checker set up and it's not detecting any issues. 

![chrome_2CqfnGZMbT](https://user-images.githubusercontent.com/73676044/211204458-6b3d38a2-dfbf-4ac1-a608-2e7c1afc95bd.png)

**Comment by Geektasticdad** [comment]
It took me a bit of digging, but the root cause was the Midi QOL module. To fix this go to Settings > Midi-Qol Configuration > Misc and change "Show Item details in chat card" to "Details: NPC + PC"

![nXRFI9TjxU](https://user-images.githubusercontent.com/73676044/211315871-f5cf9698-da3a-4f70-a8be-e705f08e5ecf.png)
