### ISSUE TITLE
(Forbidden Lands) Incorrect labels for Sleight of Hand and Animal Handling

### ISSUE THREAD

**Issue by phenomen** [Drental/fvtt-tokenactionhud#371]
#### Sleight of Hand
en.json: tokenActionHud.forbiddenLands.**sleightOfHand**
module: tokenActionHud.forbiddenLands.**sleight-of-hand**

#### Animal Handling
en.json: tokenActionHud.forbiddenLands.**animalHandling**
module: tokenActionHud.forbiddenLands.**animal-handling**

![image](https://user-images.githubusercontent.com/138311/211603918-8e52280a-33b2-4ce1-8dfd-906eb85eaf50.png)

**Comment by Larkinabout** [comment]
Fixed in release 3.0.19.
