### ISSUE TITLE
[PF2e] Show skill actions generated from workbench

### ISSUE THREAD

**Issue by NikolasTzimoulis** [Drental/fvtt-tokenactionhud#373]
[pf2e-workbench](https://github.com/xdy/xdy-pf2e-workbench) recently subsumed all functionality from a discontinued mod called PF2e Skill Sheet Actions which adds all skill actions (and some feat actions) to a separate category on the character sheet. If you could make these entries also show up on the token action HUD that would be so incredibly nice.

Thanks in advance!

**Comment by Larkinabout** [comment]
This will probably come with the eventual splitting of the PF2e system to use [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core. PF2e is next on the list to split out, but I'm currently working on overhauling the core module for performance, so may be a little while yet.

**Comment by Larkinabout** [comment]
Moved request to the Token Action HUD Pathfinder 2 repos.
