### ISSUE TITLE
Support For Dungeon Crawl Classic

### ISSUE THREAD

**Issue by Dadrak** [Drental/fvtt-tokenactionhud#376]
Hello there,

I would to see token action to be supported on Dungeon Crawl Classic : https://foundryvtt.com/packages/dcc

As always thank you for your work and wish a wonderful day

**Comment by Larkinabout** [comment]
New systems should build on [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core), which supports a separate system-based module.

I'm separating out existing systems first, so it'll be a long while before I get to look at supporting new ones. I'd suggest finding someone knowledgeable about the system to build out the Token Action HUD system module. There's no guidance as yet, but I can help out as needed. The developer can develop and release the module themselves, the only real requirement is the module's ID as Token Action HUD Core looks for: 'token-action-hud-system' where 'system' is the system's ID.

NB. there'll be a new release of Token Action HUD soon, so requirements might change a little if someone starts working on it right away.

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#29.
