### ISSUE TITLE
TokenHUD not rolling in Forbidden Lands for v10

### ISSUE THREAD

**Issue by Nametaken513** [Drental/fvtt-tokenactionhud#378]
I updated to Foundry 10 and then updated the FBL setting to 10. Everything is working great except for Token Action HUD module. It only works partially. The HUD will launch dice rolls for armor, but that’s it. If I click on the other actions, nothing. It only works partupdated everything after updating to 10. I’ve tried uninstalling and reactivating but just keep getting the same issue.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.19.

**Comment by Nametaken513** [comment]
Great! I’ll test it out :)
