### ISSUE TITLE
Warnings about deprecated methods that I come across

### ISSUE THREAD

**Issue by thatlonelybugbear** [Drental/fvtt-tokenactionhud#38]
`The Actor5e#useSpell method has been deprecated in favor of Item5e#roll`
The check for `item.data.type === 'spell'` in line 95 of dnd5e-base.js I think is not needed anymore (scripts/rollHandlers/dnd5e)

Deleted lines 95 and 96 to just use the item.roll always.

**Comment by thatlonelybugbear** [comment]
`The Document#hasPerm method has been deprecated in favor of Document#testUserPermission.`

tokenactionhud.js line 490
`return game.user.isGM || actor?.hasPerm(user, "OWNER");` -> `return game.user.isGM || actor?.testUserPermission(user, "OWNER");`

**Comment by Larkinabout** [comment]
Deprecated code has been removed with the update to Foundry VTT v10.
