### ISSUE TITLE
The installed Token Action Hud system module requires Token Action Hud core module version 1.1.

### ISSUE THREAD

**Issue by SaintLoda** [Drental/fvtt-tokenactionhud#386]
I'm receiving the error listed in the title. I just updated both Token Action Hud DnD 5e and Token Action Hud Core to version 1.2.1, and I started receiving this error. I have uninstalled and reinstalled and am receiving these errors still.

**Comment by Larkinabout** [comment]
Are you on The Forge? Uninstall Token Action HUD D&D 5e and try installing from this link: [https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/releases/download/1.2.1/module.json](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/releases/download/1.2.1/module.json)  - Making sure to untick to install from the bazaar.

**Comment by SaintLoda** [comment]
Hello, I am not using Forge. I host from a Cloud server. Uninstalling, and using the link you provided seems to have fixed it though. Thanks!
