### ISSUE TITLE
[PF2e] Two separate weapons only attacking as one

### ISSUE THREAD

**Issue by Mortavius** [Drental/fvtt-tokenactionhud#388]
In my PF2e game, I have a PC with dual pistols.  Each pistol has different enchantments; one is wounding, one is disrupting. The token action HUD shows both guns in the strikes section, but no matter which one is clicked, it only ever rolls the pistol with the wounding enchantment.

If the PC rolls from their character sheet, they can attack with the disrupting gun just fine, but using the HUD only allows one gun.

![Capture](https://user-images.githubusercontent.com/118096078/222297340-cf3c8e5c-5d98-452a-9ecf-3fda1bf2c38b.PNG)

**Comment by Larkinabout** [comment]
Please try the latest version of [Token Actiono HUD Pathfinder 2](https://foundryvtt.com/packages/token-action-hud-pf2e) and let me know if this issue is still happening.
