### ISSUE TITLE
Feature Request: In SWADE, allow the use of the Better Rolls 2 for SWADE action cards.

### ISSUE THREAD

**Issue by Deadlander** [Drental/fvtt-tokenactionhud#39]
Currently, when you use Token HUD in SWADE with BR2, it pops up the basic action card rather than the BR2 Card.  Please add an option to use the BR2 Action card instead.  :)

**Comment by Wigginns** [comment]
This already exists, you just need to select it in the Token Action HUD options:

![image](https://user-images.githubusercontent.com/3180645/147206678-8d7a8b7f-6e58-4a81-aebf-6e320ae2bc95.png)

**Comment by Drental** [comment]
oh, thanks. I didn't know.
