### ISSUE TITLE
SWADE unlinked actors roll from the actors not the token

### ISSUE THREAD

**Issue by grendel111111** [Drental/fvtt-tokenactionhud#390]
I'm sorry this is kind of hard to explain but I will try. When using better rolls 2 for SWADE and you use the action HUD it rolls the dice from the actor in the side bar. This means that when you have an active effect on a token for an unlinked actor it will not trigger when you use the HUD.

This Token has the active effect GRConfusionVul.
![image](https://user-images.githubusercontent.com/80164119/223456399-94b607d6-bb7f-412b-a934-192d6c3e2210.png)

It triggers when you make a smarts roll. 
If you make a SMARTS roll from the token you get these options:
![image](https://user-images.githubusercontent.com/80164119/223456980-13e94cc9-f101-4204-8dbb-003dcc46debe.png)

However if you roll SMARTS from the HUD the Resist confusion is not there, because it isn't on the actor on the side board:
![image](https://user-images.githubusercontent.com/80164119/223457392-fa4d5417-78f7-4a0b-83fe-9dd4fcbf1fa5.png)

Is it possible for unlinked actors to trigger what is on the token rather than what is on the base actor as a lot of active effects are tempory and only reside on the token. It isn't a problem for linked actors as they are always updating teh sideboard actor because of the link.
I hope this makes some sense.

**Comment by Larkinabout** [comment]
Closing as there is now a dedicated SWADE module for Token Action HUD Core: [Token Action HUD for Savage Worlds](https://foundryvtt.com/packages/token-action-hud-swade).
