### ISSUE TITLE
PF2e 2-weapon fighting with similar weapons

### ISSUE THREAD

**Issue by Drumar** [Drental/fvtt-tokenactionhud#395]
When a fighter (tested on fighter only so far) uses two weapons that share the same base (e.g. two Dandpatta's) but runes differ (one has flaming and shocking rune, the other none) it is clear that TAH selects "the first" (depending on how the weapons are sorted in the actor object): so, one time the runes are applied on both strikes (with different weapons) and another time on neither.

TAH should strike with the "actual"  weapon chosen.

Replicate:
- Create a fighter
- Give it a Flaming Shocking Dandpatta (rename it to "Flaming Shocking Dandpatta")
- Give it a Dandpatta (rename it to "unruned Dandpatta" so it is clear which weapon is used)
- Make a strike from either weapon from TAH
- Notice in chat that only one of the weapons was used rather than both.

**Comment by Larkinabout** [comment]
Hi @Drumar, support for Pathfinder 2 has moved to the dedicated [Token Action HUD Pathfinder 2](https://foundryvtt.com/packages/token-action-hud-pf2e) module.
