### ISSUE TITLE
Effects Block Duplicated 

### ISSUE THREAD

**Issue by cpe111** [Drental/fvtt-tokenactionhud#396]
Token Action Hud Core  + Pathfinder 2e modules active. Effect also occurs when all other modes have been deactivated. 

Selecting token and hovering over Effects tab shows two books of effects repeated one after the other. 

Foundry VTT V10 build 291
Pathfinder 2nd Edition 4.9.3

<img width="1410" alt="TokenActionHUDIssue1" src="https://user-images.githubusercontent.com/10131104/225785409-6e87be46-76e6-4603-8f06-e5faacdc4a4f.png">

**Comment by Larkinabout** [comment]
Hi @cpe111, this issue is fixed in Token Action HUD Pathfinder 2 1.3.0. If you experience any other issues, please raise them here: [Token Action HUD Pathfinder 2 Issues](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues)
