### ISSUE TITLE
Add Support: Coriolis

### ISSUE THREAD

**Issue by kbender84** [Drental/fvtt-tokenactionhud#398]
Hi,
I want to add support for Coriolis (yzecoriolis) game system based on alien handler.
I should be able to modify .js files from alien to work with yzecoriolis. I wonder, is there any guide that can help me to speed things up, or is it a straightforward as adding entry on module.json and then copying /editing each of alienrpg .js files +init.js and module.json?

**Comment by Larkinabout** [comment]
Moved request over to the Token Action HUD Core repos.
