### ISSUE TITLE
Pf2e Initiative button has disappeared after a system update

### ISSUE THREAD

**Issue by uniwars** [Drental/fvtt-tokenactionhud#400]
Hi, it seems that the button to roll initiative in the Attributes section of Token Action HUD Legacy module has disapperad, since one of the Pathfinder 2 4.10.x release but not the .4 because I found the issue before updating.

**Comment by Larkinabout** [comment]
Hi @uniwars, support for Pathfinder 2 has moved to the dedicated [Token Action HUD Pathfinder 2](https://foundryvtt.com/packages/token-action-hud-pf2e) module.
