### ISSUE TITLE
PF2E unidentified effects not hidden in TAH

### ISSUE THREAD

**Issue by DenMesh** [Drental/fvtt-tokenactionhud#403]
I believe there was a fix for this a little while back, but in my game I can't seem to make it work.

To illustrate the point, here is a scene in a test world with only TAH enabled. I add an effect (Spell effect: Light) to a character. I hide the effect (eye symbol next to its name). It still appears for both the DM and the player.

(GM view) Charsheet, spell effect hidden
![image](https://user-images.githubusercontent.com/9051037/230676623-19f3f62b-6da9-4dd5-90e0-9467587e5ef0.png)

(GM view) TAH, spell effect visible
![image](https://user-images.githubusercontent.com/9051037/230676722-00fc6517-8439-425a-b17c-41e700945f51.png)

(Player view) Charsheet, spell effect invisible
![image](https://user-images.githubusercontent.com/9051037/230676813-cad4aa51-6624-4da5-91fe-31138382e865.png)

(Player view) TAH, spell effect visible
![image](https://user-images.githubusercontent.com/9051037/230676885-ecd5adf6-12c4-43fc-9c85-a94743fe58a7.png)

Latest and greatest PF2E, TAH, Foundry 10.291

**Comment by Larkinabout** [comment]
Larkinabout/fvtt-token-action-hud-pf2e#33
