### ISSUE TITLE
hud won't stay in place

### ISSUE THREAD

**Issue by emerysaunders1** [Drental/fvtt-tokenactionhud#404]
Every time I move the hud and then click on the map or a different token, it reverts to the original placement and not the moved placement.

**Comment by Larkinabout** [comment]
Hi @emerysaunders1, what system is this for and what version of Token Action HUD are you using?

**Comment by emerysaunders1** [comment]
foundry 10, dnd5e, and token hud 3.0.19

**Comment by Larkinabout** [comment]
For D&D 5e, I would suggest moving to [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e).
