### ISSUE TITLE
Broken since D&D 2.2 Update

### ISSUE THREAD

**Issue by friction1** [Drental/fvtt-tokenactionhud#410]
<img width="1063" alt="Screenshot 2023-05-26 at 9 00 25 PM" src="https://github.com/Drental/fvtt-tokenactionhud/assets/11384891/bad34e3e-217d-4c2a-82b3-741e96e55807">

**Comment by Larkinabout** [comment]
Hi @friction1, support for D&D 5e has now moved to the dedicated [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e) module.
