### ISSUE TITLE
It vanished

### ISSUE THREAD

**Issue by St-Toha** [Drental/fvtt-tokenactionhud#414]
I had to load the world in a safe mode (it turns off all modules) and when i later turned the module on, the hud was nowhere to be found on the screen. I just dont see it anywhere, how do i reset its position or something?

**Comment by Larkinabout** [comment]
Hi @St-Toha, support for D&D 5e has now moved to the dedicated [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e) module.
