### ISSUE TITLE
Handling clicks into the empty area of a category

### ISSUE THREAD

**Issue by apoapostolov** [Drental/fvtt-tokenactionhud#416]
Can you handle clicks that click outside of any controls in a category and close the category? I find that even the default length of the area of the strike locks too much of a map space and requires the player/DM to click ESC to close the opened category and deselect the token or to move the mouse very far from the area (and it is hard to imagine how wide the category area is since it is 100% transparent) so it is very hard to deselect sometimes. For example, as shown below, clicking in the red square area should close the category even if it is inside its rendering zone.

![image](https://github.com/Drental/fvtt-tokenactionhud/assets/4083812/2370905c-bbf0-4a2f-8a89-959fa754beaf)

**Comment by Larkinabout** [comment]
Transferred to Larkinabout/fvtt-token-action-hud-core/issues/141
