### ISSUE TITLE
HUD not showing anymore

### ISSUE THREAD

**Issue by Malcoth** [Drental/fvtt-tokenactionhud#417]
Since the DND system update the action bar doesn't show at all anymore, and there's a type error in the browser console (see below)

What can I do to help diagnose and fix this?

![console_error](https://github.com/Drental/fvtt-tokenactionhud/assets/35173271/ee97f98b-eebb-424a-9007-0c2c0ca494d0)
![version_info](https://github.com/Drental/fvtt-tokenactionhud/assets/35173271/0819aca8-ecd3-471a-99d2-20ffc347dbd6)

**Comment by Larkinabout** [comment]
Hi @Malcoth, support for D&D 5e has now moved to the dedicated [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e) module.
