### ISSUE TITLE
Allow to set up an icon for main categories

### ISSUE THREAD

**Issue by happy-cujo** [Drental/fvtt-tokenactionhud#42]
Allow setting up an icon for main category that could be displayed next to text or can replace it completely (text can be shown as a tooltip on hover). The size of an image should be restricted by a module to enforce consistency, but it should retain being customizable by GM/Player.

Reasoning:
- Consistent width of the buttons
- Icons can be configured per world. That could help people with dyslexia or people that prefer visual indicators rather than text.
- The look can be customized to world setting and create more immersion or adding a little bit of a "game" look.

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#13.
