### ISSUE TITLE
Token issue creating compendium advenure module

### ISSUE THREAD

**Issue by Stountain** [Drental/fvtt-tokenactionhud#420]
🌈Spice_King — Today at 11:15 AM
Yea, the data added token action hud broke Foundry's sane limits to prevent infinite loops, lockups and crashes.

from Foundry Discord : Troubleshooting channel

**Comment by Larkinabout** [comment]
Token Action HUD Core 1.4.0 onwards saves data to json files instead of actor and user flags. There is a migration script in this version and later. For anyone with this issue that does not update to the current version, you can run this code in a macro script to clear out the old flag data:

```js
const actors = game.actors.filter(actor => actor.getFlag('token-action-hud-core', 'categories'))
for (const actor of actors) {
    actor.unsetFlag('token-action-hud-core', 'categories')
}

const users = game.users.filter(user => user.getFlag('token-action-hud-core', 'categories'))
for (const user of users) {
    user.unsetFlag('token-action-hud-core', 'categories')
    user.unsetFlag('token-action-hud-core', 'default')
}
```
