### ISSUE TITLE
[Question] Any plans to update for v11?

### ISSUE THREAD

**Issue by steveculshaw** [Drental/fvtt-tokenactionhud#422]
[Question] Any plans to update for v11?

**Comment by Larkinabout** [comment]
About the best I can do is update the version number, but there's no guarantees all systems will continue to function and it's too big for me to go through and fix every one myself.

If you're system is listed as supported by Token Action HUD Core, it might be worthwhile switching over to that module instead.

**Comment by steveculshaw** [comment]
Many thanks for all the work on a great module.

I've done a search and found that since I last looked (quite a while ago), Savage Worlds has got a plugin.
I'll switch over to that and see how things go
