### ISSUE TITLE
Does not work (or even appear) for the game system Simple Worldbuilding

### ISSUE THREAD

**Issue by spindocks** [Drental/fvtt-tokenactionhud#424]
When using the Simple Worldbuilding system, Token Action Hud Classic does not even appear within the "manage modules" window.

**Comment by Larkinabout** [comment]
Token Action HUD Classic doesn't support the Simple Worldbuilding system and no new systems are being supported by this module. Check out [Token Action HUD Core](https://github.com/Larkinabout/fvtt-token-action-hud-core) to post a request for a developer to support the system.
