### ISSUE TITLE
Is there a HUD compatible with Simple World Builder yet?

### ISSUE THREAD

**Issue by mccaffertyt** [Drental/fvtt-tokenactionhud#425]
Hi

Is there a HUD compatible with Simple World Builder yet?

If not, what would be the closest build so far? Would the OSE be the closest?

Tom

**Comment by Larkinabout** [comment]
No further systems are being supported  in Token Action HUD Classic. Check out [Token Action HUD Core ](https://github.com/Larkinabout/fvtt-token-action-hud-core). System modules are supported by other developers. If you can find someone to develop the module, or you'd like to try developing it yourself, feel free to get in touch for support.
