### ISSUE TITLE
Any chance for Cyberpunk Red compatibility?

### ISSUE THREAD

**Issue by markmillerlv** [Drental/fvtt-tokenactionhud#427]
I love Token Action HUD for D&D, and really miss it when I'm running CPR games. Any chance of a compatible module being worked on?

**Comment by Larkinabout** [comment]
There's an [issue](https://github.com/Larkinabout/fvtt-token-action-hud-core/issues/26)  open on the Token Action HUD Core repos for the Cyberpunk RED system, but all system modules are supported by other developers. If you can find someone to develop the module, or you'd like to try developing it yourself, feel free to get in touch for support.
