### ISSUE TITLE
HUD only appears when multiple tokens are selected

### ISSUE THREAD

**Issue by Westtantemala** [Drental/fvtt-tokenactionhud#430]
Hello,
I recently updated Foundry and the Module to the latest versions, and I've been running into a strange issue with my Pathfinder 2e games.

In one of them, the HUD only shows up when multiple tokens are selected, both on GM and Player side. In this case, itis also a reduced version of the HUD: 
![HUD Issues 1](https://github.com/Drental/fvtt-tokenactionhud/assets/134189422/43da5915-dd43-499c-8b3d-9461aa6b4d96)

In another of my games, the HUD does appear, on the GM side in all scenes, on player side just in one (the one that was active when the update was done). In this case, the HUD does show up fully, but its appearance is ever so slightly delayed. 

I'm pretty confused to be honest, as the settings are the same in both campaigns.

**Comment by Larkinabout** [comment]
Are you using the new Token Action HUD Core and Token Action HUD Pathfinder 2 modules? Also make sure you have Token Action HUD Classic disabled as it will conflict with the new ones.

**Comment by Westtantemala** [comment]
Yeah, I have only the Core and the PF2e Modules installed.

**Comment by Larkinabout** [comment]
Have you checked what happens with no other modules enabled? Failing that, I would also maybe try resetting the layout using the 'Reset Layout' module settting located in the Layout menu.

**Comment by pinkflumph** [comment]
I'll add that I have the same issue, but it is oddly sporadic. The "Multiple" menu shows up more or less consistently, but selecting individual tokens sometimes summons the menu and sometimes does not, for reasons that I haven't been able to trace - the same token might or might not work in any given attempt. I've also had the menu for a specific actor get stuck on screen whether that actor's token was selected or not, until multiple tokens were selected and the "Multiple" menu replaced it (tested as a GM, so this is not an issue with "always show HUD")

**Comment by pinkflumph** [comment]
Update: it appears to fail specifically for spellcasters (whether or not spells are selected in the layout), with the following error:
![image](https://github.com/Drental/fvtt-tokenactionhud/assets/99619418/26efcb7b-a1cf-48f1-b73d-336b7cadac40)

Selecting any spellcaster then leaves it stuck in the error state for some time during which the HUD doesn't load properly for any character, which made the behavior appear more sporadic than it really is.
