### ISSUE TITLE
Not a bug but a request

### ISSUE THREAD

**Issue by matthew81** [Drental/fvtt-tokenactionhud#435]
Hi, Are there any plans to add Everyday Heroes to the list of supported games? It is 5e with a few extra steps rules wise and is set in the modern day. Think it would be really cool to have this mod with that system also.

Ta, Matt

**Comment by Larkinabout** [comment]
There's a feature request over at the Token Action HUD Core repos: [https://github.com/Larkinabout/fvtt-token-action-hud-core/issues/91](https://github.com/Larkinabout/fvtt-token-action-hud-core/issues/91). System support is now entirely reliant on other developers to take up development. It might be worth asking over on the Foundry VTT Discord if there's any developers willing to work on it.
