### ISSUE TITLE
Forbidden Lands delete the extra attributes please

### ISSUE THREAD

**Issue by SwedishRabbit** [Drental/fvtt-tokenactionhud#438]
In Forbidden Lands there is two attributes in the bottom "Health" and "Resolve" that is not used and should be removed:
Swedisk translation in the picture:
![token](https://github.com/Drental/fvtt-tokenactionhud/assets/128657928/49d923ae-9767-4038-b6ad-c924bbfd02c9)

**Comment by Larkinabout** [comment]
Closing as Forbidden Lands is supported on Token Action HUD Core: https://foundryvtt.com/packages/token-action-hud-forbidden-lands
