### ISSUE TITLE
Allow removing Active Effect

### ISSUE THREAD

**Issue by happy-cujo** [Drental/fvtt-tokenactionhud#44]
Allow removing Active Effect from the HUD level. Most likely for GM only, or controlled via configuration option.
Either add a trash can icon next to the effect or change right click listener to prompt the user if he wants to remove effect from token/actor.

Reasoning:
Sometimes you want to end the effect sooner and you need to got to given character and remove the effect there. It would be a nice QoL to have an option to remove AE from token/actor from HUD level. It's easier accessible than character sheet tab.

**Comment by Drental** [comment]
can you disable the effect with the effects sheet (accessible by rightclick)? I'll try to look into this - you made good points throughout - but I am only one non-coder doing maintenance and munching on strawberries.

**Comment by happy-cujo** [comment]
Yes. There is an option toggle the AE. Both, left and right clicks are responsible for that.

The additional reasoning to this issue is to keep the HUD clean. If you toggle effect off it works correctly (AE stops being applied), but it stays on character forever, so you still need to go and removed them at some point. Also most AEs aren't transferred to different combats so there is not point in having them toggle off for the time being.

I need to dig in more into the code. Maybe I'll be able to prepare PR for that one.

**Comment by Larkinabout** [comment]
Effects can be toggled (left-click) or deleted (right-click) on the HUD in the new [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core). Your system may not be support yet but developments of this nature will continue there.
