### ISSUE TITLE
Can't turn of passive feature

### ISSUE THREAD

**Issue by RawrKrake** [Drental/fvtt-tokenactionhud#440]
I might have found a bug. My 5e players don't need to interact with passive features only with active ones. So I tried removing it from the tab, by right clicking the unlocked feature tab and removing it, but every time I refresh the world the passive feature is back. Is that a feature of the module or a bug?

**Comment by Larkinabout** [comment]
If this is for Token Action HUD Core and it is still an issue, raise an issue over here: https://github.com/Larkinabout/fvtt-token-action-hud-core/issues
