### ISSUE TITLE
HUD not working after upgrade to Pathfinder 2E system 6.5.0

### ISSUE THREAD

**Issue by S-North** [Drental/fvtt-tokenactionhud#443]
Just upgraded to pf2e 6.5.0. Token Action HUD is now compaining that it needs Token Action HUD Core module version 1.5. 
"Action HUD system module requires Token Action HUD Core module version 1.5. Install the required version to continue using Token Action HUD."
It was working fine with the same versions of Token Action HUD on pf2e version 6.4.1.
I have done a forced reload with cache cleared.

Token Action HUD Core: 2.0.1
Token Action HUD Pathfinder 2e: 1.5.17
System: Pathfinder Second Edition 6.5.0
Foundry VTT: Version 12 build 331
Browsers: latest Firefox, Edge, Chrome

**Comment by Larkinabout** [comment]
You'll need to revert back to the previous version of Tolen Action HUD Core until the system module supports the latest version.

**Comment by S-North** [comment]
Hi, thanks. When you say system module, do you mean Token Action HUD Pathfinder 2e needs work to support latest pf2e system version?

**Comment by Larkinabout** [comment]
Not quite. Token Action HUD Pathfinder 2 needs to be updated to support Token Action HUD Core 2.0+. Until that happens, install [Token Action HUD Core 1.5.7](https://github.com/Larkinabout/fvtt-token-action-hud-core/releases/download/1.5.7/module.json).
