### ISSUE TITLE
WFRP HUD - Skills not working

### ISSUE THREAD

**Issue by sladecraven** [Drental/fvtt-tokenactionhud#47]
Skills drop-down list is not working in latest Token HUD for WFRP4E

**Comment by Txus5012** [comment]
The same happens for Magic and Religion.

**Comment by gravagehulk** [comment]
The creature attacks are also not showing up again in 4.0.2 of the system. i.e. Bear "weapon" and "bite" are missing from the hud. You had fixed this in the 0.7 version of Foundry, but it's gone again now.

**Comment by Drental** [comment]
WFRP had the big update and it seems to have changed many things. I'll try to fix these during the weekend.

**Comment by Drental** [comment]
Can either of you guys check again and tell me if it's still broken?

**Comment by Drental** [comment]
The weapons get added in the trait category.

**Comment by gravagehulk** [comment]
Hi. I am seeing it again under traits. Thanks!

<img width="920" alt="Screen Shot 2021-08-07 at 10 00 55 AM" src="https://user-images.githubusercontent.com/69117052/128604563-d3fdf32f-031d-4c29-bfa4-d7ee598e1626.png">

**Comment by Larkinabout** [comment]
Weapons, Magic and Religion buttons tested as working in release 3.0.6.
