### ISSUE TITLE
Actions and Spells not shown

### ISSUE THREAD

**Issue by zappallot** [Drental/fvtt-tokenactionhud#48]
Foundry: 0.8.8
World: pf2e 2.9.1
HUD: 1.1.17

Actions and Spells are not selectable in the HUD anymore.
![image](https://user-images.githubusercontent.com/64066065/126610345-08b1a2c8-4be4-4815-85e6-af944652983f.png)

**Comment by Drental** [comment]
You have multiple tokens selected, can you reproduce an error with only one token selected?

**Comment by zappallot** [comment]
Yeah, that was the error. I must have selected multiple tokens on the old gamesession, then updated the module.
It was a user-error. It worked fine once once only one target was selected.
Thanks for the help anyways!
