### ISSUE TITLE
Certain tabs not working on one token

### ISSUE THREAD

**Issue by Triacs69** [Drental/fvtt-tokenactionhud#53]
I am using Foundry VTT 0.8.8 with D&D 5e, your latest updated for Token Action Hud. I have one token that doesn't display Inventory or Features. All other tokens work and when I create new ones they work. I wouldn't worry about it, but it is for a Player's pet and I even tried recreating it and it still has issues. Thank you

**Comment by Drental** [comment]
Hi, can you send me an export of the sheet so I can take a look at it? You can send it on discord to Drental#7146

**Comment by Drental** [comment]
closing as can't reprod.
