### ISSUE TITLE
SFRPG - Please split feats by action type

### ISSUE THREAD

**Issue by rokiyo** [Drental/fvtt-tokenactionhud#55]
Everything in the "Active Feats" and "Passive Feats" category is getting lumped together into a single misc category:
![image](https://user-images.githubusercontent.com/4364040/127766803-0812b5b8-649a-4296-8d20-1871c19e7e76.png)

Toggling the "Display miscellaneous feats" option in the Module Settings area will entirely show or hide all of these together.

It seems the the SFRPG system distinguishes between Active and Passive feats purely by whether or not the Activation Cost type is empty. The number seems to be irrelevant, and the "None" option is still considered Active... It literally needs to be set to the blank option:
![image](https://user-images.githubusercontent.com/4364040/127766906-459d2488-ef6a-4a86-97d4-155ef3d803ae.png)

Ideally I'd like to see the passive feats hidden, and the remaining ones split by action type.

**Comment by Larkinabout** [comment]
Added in release 3.0.11.
