### ISSUE TITLE
GURPS support

### ISSUE THREAD

**Issue by mjeffw** [Drental/fvtt-tokenactionhud#59]
@Drental I'm one of the developers for the Foundry implementation of the [GURPS](https://foundryvtt.com/packages/gurps) RPG. I'd like to see about adapting this very cool tool for our system. Let me know how I should proceed. Thanks!

**Comment by Drental** [comment]
Just came home from my weekend.

If you feel up to trying it on your own first you can go off the changes for forbidden lands (I need to finish this up soon) and make your own handlers, but I'm also available on weekends to go through the necessary changes.

what I'd really love is getting help to make the module open for module extensions, so it doesn't load all systems all the time.

[0001-action-handler-for-Forbidden-Lands-Co-authored-by-Ly.zip](https://github.com/Drental/fvtt-tokenactionhud/files/6951537/0001-action-handler-for-Forbidden-Lands-Co-authored-by-Ly.zip)

**Comment by Drental** [comment]
at the current time I have no intention to add support for additional systems. Closing to get a better overview of the state of the module.
