### ISSUE TITLE
"Failed to Load Resource" error message in console [Player only]

### ISSUE THREAD

**Issue by jocolamarco** [Drental/fvtt-tokenactionhud#60]
Player is logged in and sees the following error message:

![image](https://user-images.githubusercontent.com/45291719/128692652-88c779a5-f850-4de7-93c7-ef01c0744ba2.png)

I'm logged in as a GM and don't see any error message.

fvtt version: 0.8.8
dnd5e version: 1.3.6
token action hud version: 1.1.20

**Comment by Drental** [comment]
sorry for being late on updating the HUD.
I got nothing but advising a reinstall for these. it's complaining about missing files that are actually in the repo and release...
I could cut down on files that get shipped (technically down to one minified one) - but that'd complicate all debugging by more than I care for.

I've seen this one before recently (with a different file not loading). I'll keep my eyes out for something that might cause it.

**Comment by Drental** [comment]
has this since resolved itself or is this issue still ongoing?

**Comment by jocolamarco** [comment]
can be closed
