### ISSUE TITLE
Better Rolls for 5e Handler (most likely) no longer required

### ISSUE THREAD

**Issue by CarlosFdez** [Drental/fvtt-tokenactionhud#61]
I have removed the last batch of DOM hijack hijinks in favor of libwrapper shenanigans. The amount of midi/br incompatibilities surfaced have been unreal however there might no longer be any need to handle explicit compatibility with token action hud. 

I did a cursory check and it seems fine. But if any bugs surface from handler removal I'll most likely deal with them.

**Comment by Drental** [comment]
thanks. Got only one report, the click item to roll better option must be active.
