### ISSUE TITLE
Enhancement - Macro solution to add a category, sub-category, action

### ISSUE THREAD

**Issue by MJ12Studio** [Drental/fvtt-tokenactionhud#62]
If there is a way to do this from a macro/script, I haven't found it yet. I've gotten close with manual setFlag() attempts, but it never seems to work. If there was a way to do this, we could distribute custom sub-categories with our own actions for other users. Like have a macro/script that builds a custom menu.

Thanks,
Great module!

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#16.
