### ISSUE TITLE
Bug: Error when adding focus spell

### ISSUE THREAD

**Issue by Lej** [Drental/fvtt-tokenactionhud#63]
Error when adding focus spell. Hud not rendered when adding character to scene afterwards.

![image](https://user-images.githubusercontent.com/2363121/129477428-33e8783f-7ad8-4955-9ab6-46da1f02e22d.png)

![image](https://user-images.githubusercontent.com/2363121/129477442-2998c6dc-44ea-4f0a-bba5-61c40d0edcf8.png)

![image](https://user-images.githubusercontent.com/2363121/129477433-47cdd10a-cc01-4d24-8c06-fba31b7c8305.png)

**Comment by Drental** [comment]
either update your PF2e system or downgrade TAH - there was a breaking change I had to accomodate

**Comment by Drental** [comment]
(also, if the HUD doesn't show after that: run `game.pf2e.system.remigrate({from:0.639})`)
