### ISSUE TITLE
Tagmar RPG support

### ISSUE THREAD

**Issue by marcoswalker** [Drental/fvtt-tokenactionhud#65]
[tagmar_token-action-hud.zip](https://github.com/Drental/fvtt-tokenactionhud/files/7039436/tagmar_token-action-hud.zip)

Please add support for my system, the files are on the zip file.

**Comment by Drental** [comment]
Done, sorry for the wait I didn't realize this was just a Pull request effectively.

**Comment by marcoswalker** [comment]
thanks
