### ISSUE TITLE
[PF1]Condition order always changes

### ISSUE THREAD

**Issue by bnp800** [Drental/fvtt-tokenactionhud#67]
After applying conditions the order in drop-down menu will always change.
Before
![image](https://user-images.githubusercontent.com/69395973/131204220-d30dd27a-9d3a-4cce-9e81-e7d6161a08b7.png)

Enabled condition
![image](https://user-images.githubusercontent.com/69395973/131204241-be38a6c8-3f36-41b2-92a8-90b0746cb861.png)

Disabled condition
![image](https://user-images.githubusercontent.com/69395973/131204258-7543c867-7abf-41b0-b8b4-b71c6d99b44c.png)

And the order of conditions will be individual for EVERY token, which makes it totally confusing when applying conditions with this mod.

In dnd5e system this issue doesn't occur.

**Comment by Drental** [comment]
Fixed in 1.3.2
