### ISSUE TITLE
Token HUD absent for only one PC

### ISSUE THREAD

**Issue by Sweegs33** [Drental/fvtt-tokenactionhud#68]
Hello, thank you first of all for a fantastic mod for FVTT. I've recently begun a FVTT PF2E campaign (Forge server, updated to ver 0.8.9) and ran a session this past weekend. The session mostly ran smoothly except at the end where, just for one PC's token, the HUD does not appear. For the tokens of the other four PCs, the HUD appeared and worked normally. I've reloaded, recreated the in-game token and checked versions and looked for new updates several times now but this has made no difference to this perculiar problem.

Is this something previously mentioned and how might you suggest I resolve this?

**Comment by Drental** [comment]
Make sure your pf2e and TAH are up to date.
this is likely due to changes in the way focus points are handled by the system.

also check f12 ->console for any red text that appears when you click that token.

**Comment by Sweegs33** [comment]
Thanks, I ended up recreating the PC sheet and token. HUD works fine now.
