### ISSUE TITLE
Token Action HUD missing entirely for all players

### ISSUE THREAD

**Issue by gideonpepys** [Drental/fvtt-tokenactionhud#71]
I play PF2E.  Recently updated to 0.8.9, if that is in any way connected.  Since then, the HUD has not appeared when we click on a token.  The module is active.  Please let me know if you need more information.  Hope to solve the issue as your module is invaluable.

**Comment by Drental** [comment]
Are you playing on the Forge?

Can you see the Module in the Module settings?

when you press f12 and go to the console, do you see errors appearing every time you click a token or just a few far up?

**Comment by gideonpepys** [comment]
Playing on the Forge, yes.

I can see the module in module settings.

Not seeing any error messages in the console when I click a token.

**Comment by Drental** [comment]
got a second for me to log in to your world? Drental#7146 on discord or foundry@crumblinggiant.com as email. I use pf2e myself and it just works for me.

**Comment by gideonpepys** [comment]
You mean send you an invite as I would a player?

**Comment by Drental** [comment]
yes

**Comment by gideonpepys** [comment]
Sure.  I'll do that now.

**Comment by gideonpepys** [comment]
Sent the link to your email.

**Comment by gideonpepys** [comment]
Thanks for taking the time.

**Comment by gideonpepys** [comment]
<Error>
<Code>InternalError</Code>
<Message>We encountered an internal error. Please retry the operation again later.</Message>
<Detail>Get "http://10.7.36.233:26541/P-6578791723818573358/B-00476830/O-1cba104285ae1684/S-1": context canceled</Detail>
<RequestId>B2B259880D151939</RequestId>
<HostId>gMyr2rK/tbFeXa/KTZg/FrVT6j4sRIBgEZ01cL5EqxwNdfaT45PaLsIVv9PLbglIYp9nELwh2OZh</HostId>
</Error>

**Comment by gideonpepys** [comment]
<Error>
<Code>InternalError</Code>
<Message>We encountered an internal error. Please retry the operation again later.</Message>
<Detail>Get "http://10.7.36.233:26541/P-6578791723818573358/B-00476830/O-1cbf16e92f3c2f17/S-1": context canceled</Detail>
<RequestId>54EEAEB3F588A12A</RequestId>
<HostId>aDvwKt4dnLBlCieh0fHR/I8gzSL/HBlurUh+0XdO3kopV50qw7WxsRsSzi2fqgDeBwtwEaijftmj</HostId>
</Error>

**Comment by Drental** [comment]
1.3.1 should reduce how often this CDN Error occurs considerably.
I hope I'm right about this.
