### ISSUE TITLE
Unable to move the Token HUD - Always Repositions to the top left of the scene

### ISSUE THREAD

**Issue by Lobosolo85** [Drental/fvtt-tokenactionhud#73]
Like the title says.  The HUD will let me move it, but if I click off a character and then back on...it is back up at the top left of the screen.  I do not have "hover" enabled.  

Using Token Action HUD Ver. 1.3.0
Foundry 0.8.9
DND5e 1.4.2

Is this a known issue?  I seem to remember it being able to reposition until recently.

Lobo

**Comment by Drental** [comment]
fixed in 1.3.1
