### ISSUE TITLE
HUD is getting stuck on most recent menu

### ISSUE THREAD

**Issue by Alassalaur** [Drental/fvtt-tokenactionhud#75]
I have noticed an issue across several games, all PF2e, where when the HUD menu is moused over and then the cursor leaves the HUD, the HUD stays up with the most recently viewed menu open. Two players, as well as myself, have experienced it. A server restart (I'm using Forge) makes no difference. Switching focusing to another actor resolves it until the HUD is moused over again.

**Comment by Avitale34** [comment]
Came here for same reason

**Comment by Drental** [comment]
fixed in 1.3.1

**Comment by Avitale34** [comment]
Now it does not work at all and I get this error in console :(

bundle.min.js:1 Uncaught (in promise) TypeError: this.isModuleActive is not a function
    at ItemMacroActionListExtender.extendActionList (bundle.min.js:1)
    at bundle.min.js:1
    at Array.forEach (<anonymous>)
    at ActionHandler5e._doBuildFurtherActions (bundle.min.js:1)
    at ActionHandler5e.buildActionList (bundle.min.js:1)
    at async TokenActionHUD.updateHud (bundle.min.js:1)
