### ISSUE TITLE
Support for PF2E flexible casters spells

### ISSUE THREAD

**Issue by rlach** [Drental/fvtt-tokenactionhud#76]
In PF2E release 2.13.0 new way to cast spells for prepared casters was added. Unfortunately those spells seem to be stored in different way, and thus tokenactionhud can't display them. 

Since all spells can be heightened in flexible casters it could lead to unnecessary clutter and repetition of the same spells on each slot equal or higher than the original level that those are learned at. Maybe it would be better to display them line by line, with levels next to them (similar to different weapon attacks in Strikes section). So for example
`[Magic Missile] [1] [2] [3] [4] [5] [6] [7] [8] [9]`
For flexible caster on level 20, instead of listing magic missile in every level. Otherwise we'll probably end up with very large lists. And this way the length of the list will be maxed on 18 spells.
Ideally used up slots could be greyed out or disappear from the list next to the spell.

**Comment by Drental** [comment]
added in 1.3.7
