### ISSUE TITLE
Player option to disable

### ISSUE THREAD

**Issue by gregoryfl** [Drental/fvtt-tokenactionhud#77]
Since in a group not everyone wants to use Token Action HUD, an ability for either a player or the Host to be able to enable and disable individual instances of it would be great. A couple of my players have a small screen on their laptop and would prefer not having it up as it takes up too much space on the screen for them.

**Comment by Qaw** [comment]
There is an option per player : 
        "hint": "If enabled, the HUD is active for the user. Does not override the player permission setting.",
        "name": "Enable HUD for current user"
