### ISSUE TITLE
Inventory doesn't show custom containers

### ISSUE THREAD

**Issue by 1537592846** [Drental/fvtt-tokenactionhud#80]
I tried using it in Pathfinder 2e and the Inventory shows all the containers except a custom one I did (I'm an alchemist and I chose to have them in a bag, for easier clicking when using). Either change Inventory so it's able to get custom containers, or in the custom categories allow us to drag-and-drop them so it's created.

**Comment by Larkinabout** [comment]
Closing as tested as working in Foundry VTT v10.286, Pathfinder 2nd Edition v4.1.3 and Token Action HUD v3.0.10. See 'New Container' in the screenshot. Let me know if this issue still exists for you on the latest release.

![image](https://user-images.githubusercontent.com/105953297/193467522-84b3bc51-d30c-4ba6-9419-fd4ca04dd31c.png)
