### ISSUE TITLE
When creating new tabs/categories can't type a lowercase "s"

### ISSUE THREAD

**Issue by MrChessur** [Drental/fvtt-tokenactionhud#87]
So the issue is that when labeling a new custom category I can't type an s. Lowercase only. Uppercase works fine.

**Comment by Drental** [comment]
can't reproduce, did you try disabling all other modules? Especially those that might define hotkeys.
what System are you running the Action Hud with?

**Comment by MrChessur** [comment]
It seems to be a conflict with Library DF Hotkeys. "s" is how it returns to select tool apparently.
