### ISSUE TITLE
No longer able to use Better Rolls for 5e

### ISSUE THREAD

**Issue by FatGreasyWog** [Drental/fvtt-tokenactionhud#89]
So I've just recently started using Foundry again on a new PC, and with all the new module updates I'm no longer able to select Better Rolls for 5e from the module settings in this module, meaning it defaults to the inferior default Foundry rolls. Are there plans to reintegrate this?

![Screenshot 2021-09-24 163020](https://user-images.githubusercontent.com/91314907/134643609-dc8b7565-4a6f-47fd-9ef2-dad7841c5a6f.png)

Thanks.

**Comment by Drental** [comment]
check the better rolls repo for a quick guide on how to use it together with midi.

> Midi QOL: more or less works, but make sure to enable fast forward attack in the midi options. If auto hit detection is enabled in midi, you'll need to use the query roll mode in Better Rolls to have more accurate results (dual mode / triple mode will throw it off as midi does not detect edits in better rolls).
